### ISSUE TITLE
More informative warnings

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#102]
<a href="https://github.com/mpcagro"><img src="https://avatars.githubusercontent.com/u/17993540?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mpcagro](https://github.com/mpcagro)**
_Wednesday Mar 30, 2016 at 09:33 GMT_
_Originally opened as https://github.com/into-cps/INTO-CPS_Application/issues/13_

----

When I run a modified fmi version of the tank code, I get the following response from the coe-simulator:

```
java -jar coe.jar 
COE(Command line options: [port]

Now running on port 8082
[tankcontroller.fmu, tank.fmu]
[{8c4e810f-3df3-4a00-8276-176fa3c9f000}.controller.valve -> {8c4e810f-3df3-4a00-8276-176fa3c9f001}.tank.valve, {8c4e810f-3df3-4a00-8276-176fa3c9f001}.tank.level -> {8c4e810f-3df3-4a00-8276-176fa3c9f000}.controller.level]
[org.intocps.orchestration.coe.config.ModelParameter@6f5d84a3, org.intocps.orchestration.coe.config.ModelParameter@46b93fe3]
warning: Function fmi2GetMaxStepsize not found in dll
warning: Function fmi2GetMaxStepsize not found in dll
```

In this case it would be helpfull to be made aware who (the fmu unit) spawned the warning.
In the future it would be hard to track an error down if one added multiple new fmu units and warnings was shown in the way above.

**Comment by ldcouto** [comment]
<a href="https://github.com/CThuleHansen"><img src="https://avatars.githubusercontent.com/u/3479481?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [CThuleHansen](https://github.com/CThuleHansen)**
_Monday Apr 04, 2016 at 10:14 GMT_

----

I agree.

**Comment by ldcouto** [comment]
Keeping this as an open feature request.

**Comment by lausdahl** [comment]
COE 0.1.2 removed these native printf's 

See release notes: 
https://twt-gmbh.github.io/INTO-CPS-COE/
