### ISSUE TITLE
COE seem to get stuck

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#103]
<a href="https://github.com/mpcagro"><img src="https://avatars.githubusercontent.com/u/17993540?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mpcagro](https://github.com/mpcagro)**
_Friday Apr 01, 2016 at 09:39 GMT_
_Originally opened as https://github.com/into-cps/INTO-CPS_Application/issues/14_

----

When I sometimes run the into-cps COE it seems to get stuck, when running the tank and tankcotnroller fmus. I am not able to communicate further with the COE and I need to use 
"killall -9 java" in ubuntu 14.04 to stop the COE.  

```
 .......................
 INFO [Thread-2] (CoeInitialize.scala:276) - OK controller fmi2SetReal: nvr = 1
 INFO [Thread-2] (CoeInitialize.scala:276) - OK controller fmi2SetReal: #r3# = -0.09999999999999987
 INFO [Thread-2] (CoeInitialize.scala:276) - OK controller fmi2DoStep: currentCommunicationPoint = 3999.9, communicationStepSize = 0.1, noSetFMUStatePriorToCurrentPoint = fmi2True
 INFO [Thread-2] (CoeInitialize.scala:276) - OK tank fmi2DoStep: currentCommunicationPoint = 3999.9, communicationStepSize = 0.1, noSetFMUStatePriorToCurrentPoint = fmi2True
[ INFO] [1459502510.770347303]: Data
 INFO [Thread-2] (CoeInitialize.scala:276) - OK controller fmi2GetBoolean: #b4# = false
 INFO [Thread-2] (CoeInitialize.scala:276) - OK tank fmi2GetReal: #r2# = 1.387778780781446e-16
 INFO [Thread-2] (CoeInitialize.scala:276) - OK controller fmi2Terminate
 INFO [Thread-2] (CoeInitialize.scala:276) - OK controller fmi2FreeInstance
 INFO [Thread-2] (CoeInitialize.scala:276) - OK tank fmi2Terminate
 INFO [Thread-2] (CoeInitialize.scala:276) - OK tank fmi2FreeInstance
^C^CKilled
```

I think the problem is a memory leak in one of the fmu units, since I recompiled them myself.
Not sure why java is not responding and not sending me an error, but I would like to get some more debug info before it gets stuck.
I would be extremely helpfull if the COE had a CTRL+C handler implemented, 
that is able to print out information on current state before try to shutdown.
If the shutdown failes, information on why it failed would also be helpfull.
The attached link should be able to provide some pointers:
http://stackoverflow.com/questions/1216172/how-can-i-intercept-ctrlc-in-a-cli-application

**Comment by ldcouto** [comment]
<a href="https://github.com/CThuleHansen"><img src="https://avatars.githubusercontent.com/u/3479481?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [CThuleHansen](https://github.com/CThuleHansen)**
_Monday Apr 04, 2016 at 06:43 GMT_

----

Hmm yes, it should definitely not get stuck.
I will contact you soon to figure out why it is not responding.

**Comment by ldcouto** [comment]
<a href="https://github.com/lausdahl"><img src="https://avatars.githubusercontent.com/u/2575418?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lausdahl](https://github.com/lausdahl)**
_Thursday Apr 28, 2016 at 11:23 GMT_

----

We cannot reproduce this. Casper have been in contact with you so we hope you will re-check this when 0.0.6 comes out.

**Comment by ldcouto** [comment]
<a href="https://github.com/mpcagro"><img src="https://avatars.githubusercontent.com/u/17993540?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mpcagro](https://github.com/mpcagro)**
_Thursday Apr 28, 2016 at 15:08 GMT_

----

I will if the bug is still pressent with the new COE snapshot:
http://overture.au.dk/into-cps/development/latest/

**Comment by CThuleHansen** [comment]
Reopen if still an issue.
