### ISSUE TITLE
Support multiple instances of FMU where canBeInstantiatedOnlyOncePerProcess="true"

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#104]
<a href="https://github.com/CThuleHansen"><img src="https://avatars.githubusercontent.com/u/3479481?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [CThuleHansen](https://github.com/CThuleHansen)**
_Tuesday Apr 05, 2016 at 09:50 GMT_
_Originally opened as https://github.com/into-cps/INTO-CPS_Application/issues/17_

---

Some FMUs contain canBeInstantiatedOnlyOncePerProcess="true" and thereby do not support creating multiple instances using the given DLL.

Implement a solution, such that it is possible to instantiate the given FMU in different processes and thereby allow multiple instances.

**Comment by ldcouto** [comment]
@CThuleHansen status on this?

**Comment by CThuleHansen** [comment]
Will be implemented this summer

**Comment by ldcouto** [comment]
Right. Keeping as enhancement. Assigning to MS6 for now.

**Comment by lausdahl** [comment]
This is work in progress in collaboration between AU and MAN Diesel https://gitlab.au.dk/into-cps/distributed-fmu. The goal is to solve the once per process, and different architectures and machines issues, making it possible to do any combination of architecture/machine with any number of FMUs.

A working prototype exists which is being tested by Man Diesel with a case study.

**Comment by ldcouto** [comment]
@lausdahl @CThuleHansen , just to check, is this still ongoing?

**Comment by CThuleHansen** [comment]
Some progress has been made, but we have plans to enhance it further.
Simple answer to your question: Yes

**Comment by ldcouto** [comment]
That's all I need. I'm archiving the enhancements that are out of scope for INTO so we can revisit them later.

This one stays open.

**Comment by CThuleHansen** [comment]
We actually have a solution for this: http://overture.au.dk/artifactory/into-cps-distribution/org/intocps/orchestration/distribution/bundle/0.0.2/bundle-0.0.2-bundle.zip

However, it will not be integrated into the app. Archive :)

**Comment by lausdahl** [comment]
COE version 0.1.13-SNAPSHOT warns about this and suggest to use the appropriate plugin for the COE. I suggest to close this issue.

**Comment by ldcouto** [comment]
Sounds good to me.
