### ISSUE TITLE
Remove version bundles from download manager

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#111]
After the meeting at M18, we have decided to simplify things a bit for the download manager. we're going to remove the release bundle version selector and simply offer the latest version of every tool in the tool chain. Previous versions of the tools can also be downloaded but the latest version should be pre-selected.

Any limitations on versions of the tools and the app such as #63 remain in place.

**Comment by lausdahl** [comment]
Notes from AU improvements which Rasmus did not manage to complete within the time frame: 

Download stalls at 99%
See #111
 show whats already installed
 by default fetch the latest release and show that - #111 make it an option to change release version

**Comment by ldcouto** [comment]
After discussions in Paris, this issue needs to be revisited. I'm engaging with the tool providers to see where they want to go.

We will either implement this or close it.

**Comment by ldcouto** [comment]
I have gotten zero feedback about this. Given that, we are leaving things as they are.
