### ISSUE TITLE
FMU builder - FMUs not working in Mac

### ISSUE THREAD

**Issue by richardpayne** [into-cps/intocps-ui#114]
Using the line follower robot example in GitHub on Mac results in incorrect results. In Windows, the co-sim produces results as expected. I am assuming this is due to the compilation of the cross-platform FMUs of the sensor blocks.

**Comment by ldcouto** [comment]
Hi Richard,

Thanks for reporting this. Can you just confirm some things please?
* Are you referring to the FMU builder inside the app?
* What exactly are incorrect results? Does it crash, produce incorrect values? 
* Have you tried generating the FMU in its native tool and running on a mac?

**Comment by richardpayne** [comment]
Answers:

- I am referring to the FMU builder in the app. 
- The 'built' FMUs work in Windows, but not in Mac; the simulation runs, but produces incorrect results. 
- The original FMUs were generated in 20-sim but only includes windows binaries. I used these binaries to create cross-platform binaries in the app.

**Comment by ldcouto** [comment]
Gotcha, thanks. I'm assigning @lausdahl for now, he worked on the builder.

Can you elaborate more on these incorrect results? Perhaps post them? Also, would you mind testing the builder with an FMU from OM, just to help narrow down the problem.

**Comment by richardpayne** [comment]
I've uploaded a zip with two log.csv files from simulations in the app. The log-win.csv file contains correct results, and the log-mac.csv incorrect results (using Excel use a scatter plot on the x and y positions of the body). 

I will try using the OM FMUs asap.

[logs.zip](https://github.com/into-cps/intocps-ui/files/335358/logs.zip)

**Comment by ldcouto** [comment]
Thanks for the upload Richard, it's very clear. 

Yeah, the windows output is a mess

**Comment by ldcouto** [comment]
I will also go ahead and migrate this to the FMU builder repository. Please follow along there.

**Comment by ldcouto** [comment]
This issue was moved to into-cps/fmu-builder#1
