### ISSUE TITLE
Duplicate entries in the project browser

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#115]
When we open a project (with another project already open), the project browser doesn't reset properly so we end up with interesting states like the one below.

It's very easy to replicate (just open the same example twice).

![untitled](https://cloud.githubusercontent.com/assets/582801/16481790/ed3b6ad8-3ea4-11e6-9325-dea821e0a930.png)

@FlorianLapschies can you take an initial look at this, since you implemented the new browser?

**Comment by FlorianLapschies** [comment]
Fixed in commit 27d7b4.
