### ISSUE TITLE
Mark open file in project browser

### ISSUE THREAD

**Issue by CThuleHansen** [into-cps/intocps-ui#116]
In https://github.com/into-cps/intocps-ui/commit/dc45b5bf59174d92e3e699205d74c85394cb72a3 mark open file in project browser was implemented.
It seems like it is broken in the commit https://github.com/into-cps/intocps-ui/commit/92f0ef31312ebb620e35259f6f5a16d8cb59fc0a

The use case is: It is difficult to see which file is open in the main window. Therefore the open file should be clearly marked in the project browser. This can be done by using the select function on the tree. Previous issue: #67 

@FlorianLapschies I have assigned it to you, as you might have some idea of what has broken it in the commit https://github.com/into-cps/intocps-ui/commit/92f0ef31312ebb620e35259f6f5a16d8cb59fc0a

**Comment by CThuleHansen** [comment]
Hi @FlorianLapschies 
I will take over this one and move the functionality to a different function.

**Comment by FlorianLapschies** [comment]
I plan on using another instance of the w2ui sidebar to display a tree of model components and their outputs. After selecting a number of nodes others do not get deselected and remain highlighted.
This behaviour can also be observed when adding a tree with static content.

**Comment by CThuleHansen** [comment]
How is this related to the project browser?

**Comment by FlorianLapschies** [comment]
>  Shouldn't it be a new issue?
Agreed.
