### ISSUE TITLE
default-layout.css missing

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#118]
Several html pages try to load a css called `layout-default`. This looks to be related to jquery-layout which we no longer use. @CThuleHansen can you confirm? I will go ahead and remove the offending lines once you do.

**Comment by CThuleHansen** [comment]
Ahh I cannot remember.. Seems fine to remove it as it no longer exists and it seems like stuff is working :)

**Comment by ldcouto** [comment]
Alright. We'll leave it for the next release, though. Just in case something does break.

**Comment by ldcouto** [comment]
We're not getting these errors anymore. Closing.
