### ISSUE TITLE
Prepare release

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#12]
Create a gulp task to use electron packager to build distributable binaries.

**Comment by lausdahl** [comment]
When searching for something else I found this guide: https://medium.com/developers-writing/building-a-desktop-application-with-electron-204203eeb658#.5cb74kpz8

However it gave the issue here: https://github.com/electron-userland/electron-packager/issues/184 which can be solved by setting `main` in `package.json` which enabled the build package run.

**Comment by ldcouto** [comment]
Cool start. We probably need to pump it out for all platforms so I want a gulp task that automates everything. Something like https://github.com/mainyaa/gulp-electron

**Comment by lausdahl** [comment]
Yes on mine I can use the `--all` argument but then it complains about me not having wine installed. I haven't merged the app stuff to demo into master yet 92087f02490af1a5b8f703419c33861cf2d7f443 but if you want you can branch from 92087f02490af1a5b8f703419c33861cf2d7f443 and add it. I will not touch the gulp stuff.

It seems the the Electron approach was a good decision it is fast to develop and seems to run fine on both Windows and Mac (haven't tried Ubuntu/Linux yet)

**Comment by ldcouto** [comment]
Well, npm is crazy slow on my laptop (I'll show you in Stuttgart) but yeah the environment is good.

I'll take care of the gulp stuff. We'll have 1 task per platform and an aggregation task to build all. Hopefully, someone will be able to do all 3 so they can solo release. But if it's needed we can just create the release as a draft and have different people upload the binaries. 

We were not planning to do any releases before MS2 (which is about a week before the M18 plenary). Do you think it's worth it to do some alpha releases beforehand so people can start playing with the COE?

**Comment by lausdahl** [comment]
Ok, mine is also a lot faster than Caspers.

For the build stuff maybe I can at some point take a look to see if Ubuntu can build all of them. Then I can add a job on the build server that builds dev standalone apps. Then we could potentially send some of them around.

If we can manage then I think a release before the M18 would be good even it is only has some basic stuff. Maybe it could have the most essential configuration needed for the COE.

**Comment by ldcouto** [comment]
Linux also needs Wine. It's because of https://github.com/atom/node-rcedit 

So, unless you put wine on the build server, it's no good. But on windows you should be able to build all three.

Like I said, there will be a release 1 week before M18. We have 3 weeks between Stuttgart and that release. We can push out an alpha so people can replicate the features you demo at Stuttgart. The only concern is distributing the COE. We have an issue for that (#24) but it's not started yet.

So maybe we have an alpha that requires manual "installation" and starting of the COE. I assume the co-sim tab you are developing simply requires that the COE be running in the background. Is that correct?

**Comment by lausdahl** [comment]
Ok.

Yes your assumption is correct. I haven’t look into #24. I think it could be downloaded through the download manager which Anders is implementing but it will still need some sort of control interface inside the app I think.

I think having the app even if the user still needs to start the COE manually is a good step forward. Now everything is done in the terminal (based on the support we have responded to).Three weeks is not a lot of time so completing this task as well maybe too much. If we wait then Anders should also have completed the download manager.

**Comment by ldcouto** [comment]
When we set up #24, the plan was to just bundle the coe jar inside the app. At the time, the download manager was not a part of the app at all. That's a recent addition, suggested by Peter I guess. I haven't seen any commits from Anders yet.

So, we will do some alpha releases with the independent COE. But we still need minimal file handling and COE interactions to be implemented.

How are people producing the co-sim configurations right now? Via modelio?

**Comment by lausdahl** [comment]
Ok.

I think must of the users create them by hand from http://overture.au.dk/into-cps/site/simulation/example.html <http://overture.au.dk/into-cps/site/simulation/example.html> at least the ones we have been contacted by.

**Comment by ldcouto** [comment]
Ok, we'll consider that configuration handling for the beta releases only. The alpha will just be a way to submit files to the coe.

**Comment by lausdahl** [comment]
I will take a look at automating the packaging so we can produce these the standalone bundles automatically.

**Comment by ldcouto** [comment]
Are you talking about a gulp task for electron packager? I have that done. Just need to fill it out for the remaining platforms.

I can do it by tomorrow, or show you what I have and you can take over.

**Comment by lausdahl** [comment]
I have them here locally just copied your stuff, but they never complete if I call them.

I'm working on the automation part. I added a job here which runs docker and builds all platforms: https://build.overture.au.dk/jenkins/job/into-cps-ui

Not finished yet, need to fix some user permissions, and possibly get an oAuth token to it can tag and upload a release draft with the result.

The docker image includes wine etc. so it can build all of it.

I can push the gulp additions I made, it is just extending yours.

**Comment by ldcouto** [comment]
Are you looking at ldc/pkg-task?

None of the gulp plugins for electron-packager seemed to work for me. But if you invoke the packager directly, it works fine.

**Comment by lausdahl** [comment]
ok thats also what happens for me both on darwin and linux. If I call it manually in the terminal it works but if I use gulp then it hangs

**Comment by ldcouto** [comment]
No, sorry. I didn't explain it right.

If you use electron-packager directly in gulp (without a gulp plugin), you can use the API calls to build the packages. That worked fine for me. No terminal involved.

**Comment by lausdahl** [comment]
I tried this:


```
var packageJson = require('./package.json');
// P]ackage app into binary

gulp.task("create-package-darwin", function(callback) {
    var options = {
        dir: '.',
        name: packageJson.name,
        platform: "darwin",
        arch: "x64",
        version: "0.36.0",
        overwrite:true,
        icon: 'into-cps-logo.png.ico',
        out: 'pkg',
        "app-version": packageJson.version,
        "version-string": {
            "CompanyName":  packageJson.author.name,
            "ProductName": packageJson.productName
        }
    };
    packager(options, function done (err, appPath) {
        if(err) { return console.log(err); }
        callback();
    });
});
```

it didn’t work is this using the electron-packer?

I think it could be nice if there could be a gulp goal like “gulp package” that the build server could invoke so all was configured in gulp. Can you look into this. Sounds like you know more about this than I do.

**Comment by ldcouto** [comment]
Yeah, that works for me. You can grab the head of ldc/pkg. I just build the app with it, no problems (merged with master). Could be a windows thing. I will try at home with my Mac.

My plan was to have the following:
* gulp package-win
* gulp package-mac
* gulp package-Linux
* gulp package-all

The build server can just invoke the last task. 

I will look into it.

**Comment by lausdahl** [comment]
Can you merge this into master then I will ask the server to build “gulp package-all”


I’m running with this now:

cd /opt/jenkins-workspace && npm install && gulp init && gulp && \
electron-packager . into-cps-application --platform=darwin --arch=x64 --version=0.36.0 --out=pkg --icon=into-cps-logo.png.icns --overwrite &&\
electron-packager . into-cps-application --platform=linux --arch=x64 --version=0.36.0 --out=pkg --icon=into-cps-logo.png.icns --overwrite &&\
electron-packager . into-cps-application --platform=win32 --arch=all --version=0.36.0 --out=pkg --icon=into-cps-logo.png.icns --overwrite && chown -R 105 . && chgrp -R 111 .

it outputs to: https://build.overture.au.dk/jenkins/job/into-cps-ui/ws/pkg/ <https://build.overture.au.dk/jenkins/job/into-cps-ui/ws/pkg/>

**Comment by ldcouto** [comment]
Will do. If my old build server login still works, I can trigger some builds.

**Comment by lausdahl** [comment]
it does for the open one where overture also exists

**Comment by ldcouto** [comment]
The tasks are up on master now.

I can't test the Darwin build on Windows because of symlink (see https://github.com/electron-userland/electron-packager/issues/71)

I'm also having some permission problems on the Linux builders.

**Comment by ldcouto** [comment]
Update: I can build the linux binaries now. I don't have a Linux machine to test them though.

**Comment by lausdahl** [comment]
I will push a small change in a minute and ask the server to run gulp package-all

**Comment by lausdahl** [comment]
do I need to call gulp build before gulp package-all?

**Comment by lausdahl** [comment]
ok this is the result http://overture.au.dk/into-cps/into-cps-app/master/Build-30_2016-05-25_16-21/ <http://overture.au.dk/into-cps/into-cps-app/master/Build-30_2016-05-25_16-21/> with my tweak in master. Can you run any of the windows ones?

the mac one seems to be ok, tested it locally with version and all.

**Comment by lausdahl** [comment]
I also think the inclusion needs to be adjusted on mac it looks like everything is included twice and that the example also gets included. Isn't it only dist + the main stuff that is needed.

**Comment by ldcouto** [comment]
Yeah, gulp build is need. There is no way to specify task dependencies in gulp so you can do something like `gulp build && gulp package-all`.

The inclusion needs to be fixed in a big way. Basically, we need to go to a 2 package.json structure: 1 for development and one for the app itself. Right now, we bundle all the development modules (like gulp and its plugins) into the app.

But this is another big repo change that we will have to discuss at M18. For now, I think we just deal with the very big app.

**Comment by ldcouto** [comment]
Downloaded windows app. Runs fine. For some reason, the icon is not set (my local build sets it).

**Comment by lausdahl** [comment]
ok I think I read something about a bug with icons and windows at some point.

The server runs this:

```bash
npm install --no-progress && gulp init && gulp && gulp package-all
cd pkg
for i in */; do zip -r "${i%/}.zip" "$i"; done
```
and then uploads all `*.zip` from `pkg`

I think you can do/plan the rest from the repository as long as you make `gulp package-all` do whats needed to make the bundles.

**Comment by ldcouto** [comment]
Ok, I will try that.

By the way, the packager outputs to package, not pkg. It's also possible to get gulp to zip it up for us. But I'm not sure if it's useful.

I can change that, of course. We should probably settle on a specific name for the folder where we output the packages to :)

--ldc

**Comment by lausdahl** [comment]
I set output to pkg thats what the server runs with now, so if you change it you have to change it in both places.

**Comment by ldcouto** [comment]
Ok, pkg is fine. I'll update the task description on the wiki.

--ldc

**Comment by ldcouto** [comment]
Alright, it seems to work. I tested both windows versions and they work fine.

@lausdahl, can you test the MacOs build (https://build.overture.au.dk/jenkins/job/into-cps-ui/ws/pkg/into-cps-app-darwin-x64.zip)

We also need someone to test the Linux build. @FlorianLapschies , you're on Linux right? Can you test if https://build.overture.au.dk/jenkins/job/into-cps-ui/ws/pkg/into-cps-app-linux-x64.zip works?

I've also added a small release procedure page to the wiki:https://github.com/into-cps/intocps-ui/wiki/Release-Procedure

**Comment by lausdahl** [comment]
It does not work at all. None of the browser items open the right thing. I think the path is wrong or something.

Uncaught (in promise) TypeError: path must be a string
An error occured when loading the file: /Users/kel/data/into-cps/intocps-ui/demo-project/Multi-models/watertank-1/Experiment 1 - Watertank 1 control

I’m pretty sure that no such file exists.

**Comment by ldcouto** [comment]
Hmm, did you try creating a new project?

**Comment by lausdahl** [comment]
Nothing from the project browser related to config files worked in the link you send, it works however in development so just pick a newer build for the alpha release. I think they did something wrong when they changed to the new project browser. I saw that Casper also had problems with development around the time where you send the build link.

**Comment by ldcouto** [comment]
Alright, I'll set up a new one. Is Jenkins building on pushes or do we need a manual trigger?

**Comment by lausdahl** [comment]
pushes to master

**Comment by ldcouto** [comment]
Alright, I've tested a couple of downloads from the build server and some local builds. The task works fine. I'm closing this issue.
