### ISSUE TITLE
String parameters cannot be ser in multi models

### ISSUE THREAD

**Issue by lausdahl** [into-cps/intocps-ui#120]
String parameters cannot be set in multi models. It is now shown in the list of available parameters

**Comment by CThuleHansen** [comment]
Do you have any example of a multimodel with a string parameter that I can use for testing?

**Comment by CThuleHansen** [comment]
The reason for the bug is that the view only takes the parameters from the mm.json, not from the modeldescription.xml

**Comment by CThuleHansen** [comment]
This is related to the FMU export and not the app. The app works.
