### ISSUE TITLE
Show COE Server status launcing should be grayed out when already started

### ISSUE THREAD

**Issue by pglvdm** [into-cps/intocps-ui#125]
This is a minor issue. The use of the COE abbreviation is also questionable as I see it for new users

**Comment by ldcouto** [comment]
What term would you suggest instead? Keep in mind that it needs to fit reasonably in the menu entry.

**Comment by pglvdm** [comment]
I suggest to write the "Co-simulation Orchestration Engine" out in full. The project name will for most users be a longer path than this anyway...
