### ISSUE TITLE
At startup of the App on my mac there are extra boxes that shouldn't be there

### ISSUE THREAD

**Issue by pglvdm** [into-cps/intocps-ui#127]
![image](https://cloud.githubusercontent.com/assets/4736022/16901633/a62d39b6-4c49-11e6-9565-ccda813fb8ce.png)

**Comment by ldcouto** [comment]
Those are the dev tools. They can be hidden in the view menu. They should be hidden by default, though. Are you sure you did not open by accident once? They will persist once switched on.

**Comment by pglvdm** [comment]
I am sure that I did not open it by accident once BUT they were not hidden in the VERY first version of the App I tried on my mac. Maybe that is the route course of it. But then how can I remove all app info from the mac so I can see if it goes away?
