### ISSUE TITLE
Restarting the app is still binding the 8082 port

### ISSUE THREAD

**Issue by pglvdm** [into-cps/intocps-ui#128]
After a crash/mistake with the App when you close it entirely down and try to restart the COE in a new instance you get:
COE(Command line options: [port]

Version: 0.0.8
Now running on port 8082
Couldn't start server:
java.net.BindException: Address already in use

**Comment by ldcouto** [comment]
I cannot reproduce this. I've turned on the COE, crashed the app, closed everything. I can restart the app and launch the coe as normal.

What are the steps to cause this crash/mistake?

**Comment by pglvdm** [comment]
I guess that the steps are:
1. Start the COE server
2. select a variable that cannot be viewed in the graph (see other issue)
3. start the co-simulation (resulting in a crash)
4. closing all visible windows (and removing the app from the launch line at the bottom of the screen
5. Restarting the app and trying to start the COE server (if one open a list of processes running it seems that that remains one java thread related to this so iff that is killed manually from the process overview it seems to work again)

**Comment by lausdahl** [comment]
This is fixed in COE 0.1.4
