### ISSUE TITLE
Changing to a new project after successful co-simulation is not able to co-simulate

### ISSUE THREAD

**Issue by pglvdm** [into-cps/intocps-ui#129]
When you start co-simulation for such a new project you get: Starting simulation: FAILED...

**Comment by pglvdm** [comment]
Actually it looks like this behaviour is also caused by being able to select variables that cannot be viewed in the graph. I suggest that it should not at all be possible to select such variables.

**Comment by ldcouto** [comment]
I cannot reproduce the first part of this bug. I can run co-sims, open or create new projects and run more co-sims.

What do you mean by "variables that cannot be viewed in the graph"

**Comment by pglvdm** [comment]
You can only view variables that are plain numbers in the graph (as far as I understand it), so if you for example for the line-following robot select one of the positions you will get the error I reported. My suggesting is that only variables that are numbers (and thus can be viewed in the graph) can be selected.

**Comment by ldcouto** [comment]
@pglvdm , can you confirm if this is still present in the 2.0.0 version?

**Comment by pglvdm** [comment]
I can confirm that this seems to be fixed now.

**Comment by ldcouto** [comment]
Great. Closing
