### ISSUE TITLE
Simplify opening new view from browsercontroller

### ISSUE THREAD

**Issue by CThuleHansen** [into-cps/intocps-ui#131]
Currently the projbrowserview does the following when an item is double clicked:

```
Deinitialize
if (deinitialize was success)
{
   select new view in browserview
   open new view 
}
```

Instead, the flow can, without any loss of functionality be changed to:

```
OpenNewView
if(openNewView was success)
{
   select new view in browserview
}
```

This requires:
- openView in init.ts to return a boolean
- each menuhandler.open\* to return the boolean from openView
- dblClickHandler in ProjectBrowserItem to return a boolean
- this.tree.on dblclick in browsercontroller must change flow. as shown in code above.

This simplifies the interface between projbrowsercontroller and init.ts without any loss of functionality.
All of the view opening functions must use the menuhandler for this to work. Currently all except: RTTester.openFileInGUI(path); uses it. @FlorianLapschies will fix RTTester.openFileInGUI(path); in BrowserController.

**Comment by ldcouto** [comment]
@CThuleHansen  anyone working on this?

**Comment by FlorianLapschies** [comment]
RTTester.openFileInGUI(path) is called to open files in the external RT-Tester GUI program and not for opening files in the into-cps app. Therefore, the currently displayed view is not to be replaced upon double click.
I am not sure whether that this double click action fits well into the proposed scheme.

**Comment by ldcouto** [comment]
You can change it to a right-click menu option if you prefer. Personally, I don't mind keeping it as double-click. Hopefully, we will soon have a user manual to explain all this stuff

**Comment by ldcouto** [comment]
Now that we have a user manual, I'm closing this.
