### ISSUE TITLE
Create Co-simulation Configuration context menu used \\ on Windows

### ISSUE THREAD

**Issue by kgpierce** [into-cps/intocps-ui#135]
The multimodel_path entry on Windows uses \\ which then fails to parse if the same project is used on Mac. For example...

{"startTime":0,"endTime":10,"multimodel_path":"Multi-models\\Test\\test.mm.json","livestream":{},"algorithm":{"type":"fixed-step","size":0.1}}

**Comment by richardpayne** [comment]
I can confirm this, changing from

> {"startTime":0,"endTime":10,"multimodel_path":"Multi-models\\3-UAV-Non-3D\\3-UAV-Non-3D.mm.json","livestream":{},"algorithm":{"type":"var-step","initsize":1e-9,"size":[5e-9,10.1],"constraints":{}}}

to 

> {"startTime":0,"endTime":10,"multimodel_path":"Multi-models/3-UAV-Non-3D/3-UAV-Non-3D.mm.json","livestream":{},"algorithm":{"type":"var-step","initsize":1e-9,"size":[5e-9,10.1],"constraints":{}}}

now works in Mac. I had previously had the error:

> Error: Could not parse config.
> Message: Error: ENOENT: no such file or directory, open '/Users/nrjp6/Documents/Projects/INTO-CPS/INTO-CPS_Git/case-study_uav_swarm/Multi-models\3-UAV-Non-3D\3-UAV-Non-3D.mm.json'
> Path: /Users/nrjp6/Documents/Projects/INTO-CPS/INTO-CPS_Git/case-study_uav_swarm/Multi-Models/3-UAV-Non-3D/Experiment 1/3uav-exp-1.coe.json

**Comment by kgpierce** [comment]
Using forward slash as a path separator works on Windows.
