### ISSUE TITLE
Results directories not in chronological order by default

### ISSUE THREAD

**Issue by kgpierce** [into-cps/intocps-ui#137]
The date format of results directories means that they are not in chronological order when sorted by name. E.g.

R_01-08-2016_11-14-12
R_01-08-2016_11-59-30
R_29-07-2016_12-22-58
R_29-07-2016_12-36-27

The format used by Crescendo has the date revered in the ISO style placing newer results at the end:

R_2016-07-29_12-22-58
R_2016-07-29_12-36-27
R_2016-08-01_11-14-12
R_2016-08-01_11-59-30

**Comment by richardpayne** [comment]
An additional comment is that the date formatting on Mac and Windows differs. In Windows:
R_01-08-2016_11-14-12
(R_DD-MM-YYYY_HH-MM-SS)

In Mac:
R_8-11-2016_11-17-26_AM
(R_M-DD-YYY_HH-MM-SS_AM/PM)

**Comment by ldcouto** [comment]
To be revisited after INTO-CPS.
