### ISSUE TITLE
Improve COE Server Status Console usability

### ISSUE THREAD

**Issue by kgpierce** [into-cps/intocps-ui#138]
When running multiple co-simulations in a row, it can be hard to track which console messages are from which run. This could be improves with some simple 
- Add a "Clear Console" button to remove old information. 
- Add a timestamp when the run starts.
- Separate runs from each other visually, e.g. vertical whitespace, or a separate outlined div for each.

**Comment by ldcouto** [comment]
We'll revisit the two remaining features after INTO-CPS
