### ISSUE TITLE
Downloader does not install or unpack tools

### ISSUE THREAD

**Issue by kgpierce** [into-cps/intocps-ui#144]
The functionality is in the code but it doesn't seem to be called?

**Comment by CThuleHansen** [comment]
A new unzipper has been implemented. However, the functionality is just not being called.

**Comment by ldcouto** [comment]
I wouldn't expect a "downloader" to unzip or install anything 
/shrug
I guess we could implement this but I would honestly rather not

**Comment by ldcouto** [comment]
Let's revisit this after INTO-CPS. I remain unconvinced that this is useful but we can have the discussion.
