### ISSUE TITLE
Incorrect FMU paths in co-simulation

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#145]
On windows, at least, there is some kind of problem with the FMUs path are sent to the COE.

If I try t run any co-sim, it fails with the following COE exception:
```
Failed to load and parse model defintion in: file:\C:\Users\CoutoLD\dev\workspaces\into-app\example\FMUs\TestModel_01.fmu 
Reason:  File not found: C:\Users\CoutoLD\Downloads\file:\C:\Users\CoutoLD\dev\workspaces\into-app\example\FMUs\TestModel_01.fmu
```

It looks it's prepending the COE location to the FMU path. I've tried many variations on this (coe in default location and elsewhere, COE started manually and through the app) but it always yields the same result.

**Comment by CThuleHansen** [comment]
Can you change the log4j.properties in the root of the coe.jar to: `log4j.rootLogger=ALL, stdout, R` and paste the log?

**Comment by CThuleHansen** [comment]
Related to wrong COE version.
