### ISSUE TITLE
Not  able to consistently copy out an error

### ISSUE THREAD

**Issue by mpcagro** [into-cps/intocps-ui#146]
I am running Ubuntu 14.04 and testing the "into-cps-app-2.0.0-rc-linux-x64".
It seems like the right click menu option is disabled in the UI, so it is unclear when I have copied something out like an error. The Ctrl+C and Ctrl+V seems to work most of the time, but it would be nice to have the standard clip, copy, paste menu.

**Comment by ldcouto** [comment]
It's true the class right-click menu is disabled. Although it would be more accurate to say it's not implemented :)

The main reason for this is that we need the right click menu for certain actions (such as creation of new Multi-Models).

But I agree that, for the COE log and Main View, it would be nice to have the menu. @CThuleHansen , can we fit this in as an enhancement?

**Comment by mpcagro** [comment]
Another possibility would be to create a copy button for the output inside the UI !

**Comment by ldcouto** [comment]
Do you mean exporting the coe log? I think the coe already creates a log file in the folder where it's run.

You also have the copy entry in the edit menu.

**Comment by mpcagro** [comment]
I just want to have a copy button, when I got errors like the ones in:
https://github.com/into-cps/intocps-ui/issues/147
I had the CTRL-C option disabled because of a bug in my keyboard, so I needed to use external keyboard.

**Comment by CThuleHansen** [comment]
I am not sure I understand. What are you trying to copy?

**Comment by ldcouto** [comment]
Yep, that's the thing.

For the record, there are some alternatives currently:
* Ctrl-C
* (in development mode): Edit Menu > Copy
* the coe.log file that is generated in the same folder as the COE contains most of the COE log (but see #151)

**Comment by ldcouto** [comment]
I think there are enough options to copy out COE logs, especially considering the generated log files will now cover the full output, per #151.

Closing.
