### ISSUE TITLE
Running std example with UI

### ISSUE THREAD

**Issue by mpcagro** [into-cps/intocps-ui#147]
I normally use the COE directly intead of using the UI, but I attempted to use the UI again today.
This video below shows the response I get, when trying to run the COE with the std example:
https://www.youtube.com/watch?v=YLdQyZFDYPg&feature=youtu.be
It also confused me that I can launch the coe multiple times, but not change the port.
I am unsure If these are bugs or me using the UI in a wrong way.

**Comment by ldcouto** [comment]
Martin, 

Seems like you are running the 2.0.0 RC of the app with the 0.0.6 COE. Version 2 of the app only works with COE 0.1.2 or higher. Also, the only examples that currently work are 3 Watertanks and UAV. If you try to import from the app, they should be the only ones to appear.

Can you give it another try and reply back?

**Comment by mpcagro** [comment]
This is what I got when I upgraded the COE:
```
COE(Command line options: [port]

Version: 0.1.2
Now running on port 8082
Server started, Hit Enter to stop.

ERROR [NanoHttpd Request Processor (#1)] (RequestProcessors.java:251) - Internal error in initialization
java.lang.Exception: {WaterTank}-file:////home/martin/.config/INTO-CPS APP/intoCpsApp/tmp/install_temp/case-study_single_watertank/FMUs/singlewatertank-20sim.fmu: Illegal character in path at index 37: file:////home/martin/.config/INTO-CPS APP/intoCpsApp/tmp/install_temp/case-study_single_watertank/FMUs/singlewatertank-20sim.fmu
at org.intocps.orchestration.coe.json.InitializationMsgJson.getFmuFiles(InitializationMsgJson.java:163)
at org.intocps.orchestration.coe.httpserver.RequestProcessors.processInitialize(RequestProcessors.java:247)
at org.intocps.orchestration.coe.httpserver.RequestHandler.initialize(RequestHandler.java:280)
at org.intocps.orchestration.coe.httpserver.RequestHandler.handleRequest(RequestHandler.java:177)
at org.intocps.orchestration.coe.httpserver.NanoWSDImpl.serveHttp(NanoWSDImpl.java:36)
at fi.iki.elonen.NanoWSD.serve(NanoWSD.java:861)
at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:925)
at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.URISyntaxException: Illegal character in path at index 37: file:////home/martin/.config/INTO-CPS APP/intoCpsApp/tmp/install_temp/case-study_single_watertank/FMUs/singlewatertank-20sim.fmu
at java.net.URI$Parser.fail(URI.java:2848)
at java.net.URI$Parser.checkChars(URI.java:3021)
at java.net.URI$Parser.parseHierarchical(URI.java:3105)
at java.net.URI$Parser.parse(URI.java:3053)
at java.net.URI.<init>(URI.java:588)
at org.intocps.orchestration.coe.json.InitializationMsgJson.getFmuFiles(InitializationMsgJson.java:160)
... 8 more
```
I know I would also need to update my examples, so I am aware of the reason for the error.
I noticed that the UI removes my old version of the COE, since it is using the same install folder and is using the name coe.jar. It would be nice to be able to have multi version of the COE, like normal package managers are able to handle. Like one for testing and one for development.

The way linux normally handles this is creating subfolders for each version. 
So all files related to release 0.0.8 is stored in its own folder.
Also if UI 2.0 RC cannot use release 0.0.7 (COE - 0.0.6, overture 2.3.6 ....), it should not be possible to download it using this UI.

One could adapt a standard OS independent package manager to handle all the interdependency rules, to avoid writing it from scratch. But again I will not be the main user of the INTO-CPS app, since I like to control the process of running the COE manually.

**Comment by ldcouto** [comment]
I agree that it would be nice to cope with multiple versions and such. But the download manager was not really designed as a packager manager or something of the sort. It's just meant to be a little convenience tool to save the users the effort of manually downloading the various tools. That's also why it lets you download incompatible versions.

Personally, I don't like tools that download other tools so I never use it myself.

That said, the co-sim view in the app should probably detect and reject invalid COE versions.

**Comment by mpcagro** [comment]
I totally agree with your assessment on the UI. 
I also like to download the individual parts myself.
A simple way to cope with multiple versions would be this:
I noticed the UI created the folder structure:
/home/martin/.config/INTO-CPS APP/intoCpsApp/tmp/install_temp

This would just need to be changed to:
/home/XX/.config/INTO-CPS APP/intoCpsApp/tmp/install_temp/r_0_0_8
/home/XX/.config/INTO-CPS APP/intoCpsApp/tmp/install_temp/r_0_0_7
/home/XX/.config/INTO-CPS APP/intoCpsApp/tmp/install_temp/r_0_0_6
/home/XX/.config/INTO-CPS APP/intoCpsApp/tmp/install_temp/r_0_0_5
/home/XX/.config/INTO-CPS APP/intoCpsApp/tmp/install_temp/r_0_0_4

Where /home/XX/ is the the XX user path in Linux.
One then selects one of the allowed release candidates (that is able to run with this UI release).
Then users will have matching versions of COE, Overture, Openmodellica ... for simulation.
This should be a solution that would work on all operating systems.
Again this is just a sugestion, that would make it easier for non-experienced users.

**Comment by mpcagro** [comment]
Hmm, I tried to change to the new versions of the example:
This was the error I got:

```
Error: Could not parse config.
Message: Error: ENOENT: no such file or directory, open '/home/martin/into-cps-projects/case-study_three_tank/Multi-models/Non-3D/Non-3D.mm.json'
Path: /home/martin/into-cps-projects/case-study_three_tank/Multi-Models/Non-3D/Experiment 1/Non-3D.coe.json
```

**Comment by CThuleHansen** [comment]
Try without spaces

**Comment by CThuleHansen** [comment]
Can you try without spaces?

**Comment by lausdahl** [comment]
Space in the path is not supported by the app. It keeps spaces as ' ' but it should be encoded as `%20` according to http://stackoverflow.com/questions/1634271/url-encoding-the-space-character-or-20

This is also not handled in the Overture FMU tool wrapper.

**Comment by mpcagro** [comment]
I think the best approach would be to always use "Experiment_1" or "Experiment-1".

**Comment by ldcouto** [comment]
Agreed. See #153 for tracking the standardisation of example names.
