### ISSUE TITLE
Plotting function scripting

### ISSUE THREAD

**Issue by mpcagro** [into-cps/intocps-ui#148]
When I look at the plotting function in the UI, it seem to only support time-variant functionality.
I am not sure what kind of plotting lib is being used, but it would be nice to be able to run something similar to a matplotlib script for plotting. It would allow the users to utilize the different kinds of plots that been developed for most std tools. Examples of what could be relevant to plot are:
- XY-plot (X is not time but a variable, std in tools like 20-sim, openmodellica, matlab, mathematica, python,gnuplot, ...)
- Log and Log2 plots
- FFT plotter
- Boxplot
- Polar plots
- Histrogram
- State based plots
- Async Message transmission 
- 2D animation

**Comment by mpcagro** [comment]
Personally I just run the COE directly and have a plotting FMU that is parsing the relevant  values to python(matplotlib). But this is more of a functionality I develop for myself, to support my design process.

**Comment by lausdahl** [comment]
@ldcouto can you asses if there is resources to do this?

**Comment by mpcagro** [comment]
An option would be to give access to the online COE variables directly and just provide a simple script example the user could adapt. But again I will not be the main user of the UI and I agree this is more of an long term enhancement.

**Comment by ldcouto** [comment]
I guess it's possible? Plotly plots are highly configurable so we could try to inject user-written javascript to customise the plots.

But I am not sure how valuable this is. You get all the variables in the result file and these can be plotted however you want. I use the plots in the app just to give a quick idea and plot more complex stuff with R from the results file. The app plots are also limited in terms of export features.

Might be a nice exercise for someone new to get familiar with the tech but I don't see it as a priority worth assigning a dev to. Maybe if more users ask for it? Martin seems to be the only who cares for plots so far and he already has a solution.

**Comment by mpcagro** [comment]
Agreed on that it might be unneeded ldcouto, but it depends on what the UI is used for.
I think it is very unclear what the purpose of UI is from an industrial perspective. 
This makes it hard come up with input for the UI, since the purpose is unclear.

To be honest I currently prefer to do without it, since it only provides a development overhead.
I think this is a challenge that needs to be addressed by the UI development team, if the intention is that industrial partners should utilise this tool. 

Again I think the purpose is unclear and looking at current state-of-art in Robotic a UI main interface it not the way to go. So I think I am again attempting to find uses for the UI, but is comming up with no good idea's.

**Comment by ldcouto** [comment]
If your feedback is that "the UI provides me no value", that's perfectly fine and it's good feedback in itself.

The vision for the UI is that it will enable stakeholders who are not experts in any of the modelling notations to execute co-simulations. I don't think we have any such stakeholders in our case studies.

This is perhaps a wider discussion and one that I am happy to bring up at the plenary but, if you will allow me to flip the question, what would you want out of the UI?

**Comment by mpcagro** [comment]
I think i get the intended purpose now and this I should not use to much time on it.

If I wanted something extra out of the tool, it would be the beforementioned ability to supervise variables online via plotting. Simulation can run for 500-600 sec, but it would be nice to stop it if it becomes clear that it there is an error already after 5 sec.
A XY-plot for a robot pose(x,y, theta) could be an example, to ensure the controller one is developing is doing what you expect. I do not see this as DSE functionality since it would be more of a support tool for development (trial-and-error).

**Comment by ldcouto** [comment]
I believe the COE streams the variables already -- this is what's used for the plotter. @CThuleHansen can you confirm?

It should not be too difficult for users to script (python or whatever) that plots these values as they come.

**Comment by CThuleHansen** [comment]
Yes, the COE has livestreaming

**Comment by ldcouto** [comment]
I assume this is documented somewhere?

**Comment by ldcouto** [comment]
To be revisited after INTO-CPS.
