### ISSUE TITLE
COE logs cropped

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#151]
If I run a co-sim, the `coe.log` file seems to be cropped.

After running a single co-simulation, I have two log files: coe.log and coe.log.1. Neither are incomplete, both together and on their own. I also attach the full log output that gets sent to the console:

[fulllog.txt](https://github.com/into-cps/intocps-ui/files/444669/fulllog.txt)
[coe.log.txt](https://github.com/into-cps/intocps-ui/files/444673/coe.log.txt)
[coe.log.1.txt](https://github.com/into-cps/intocps-ui/files/444671/coe.log.1.txt)

**Comment by CThuleHansen** [comment]
This issue is fixed in the next version of the COE.
A log file can now reach 10 MB instead of 100KB. Once a file has reached 10 MB it will be compressed and a new log file will be created. A total of 500 compressed log files and 1 active log file is allowed, which means a total of 5010 MB in total.
