### ISSUE TITLE
Error: Could not parse config

### ISSUE THREAD

**Issue by Tom4444** [into-cps/intocps-ui#152]
I tried to run the INTO-CPS app release candidate 2.0.0.0 in a virtual machine running Kubuntu 16.0.4 64-bit, however I was not able to run the three tank example. I tried importing it via the options File->Import Example Project and Import Project from Git, and I also cloned the example myself from the GIT page and opened it from the app. The following goes wrong:

Under Multi-Models->Non-3D->Experiment1 I get under Configuration the following error:

Error: Could not parse config.
Message: Error: ENOENT: no such file or directory, open '/home/bkh/Downloads/into-cps-app-2.0.0-rc-linux-x64/case-study_three_tank/Multi-models/Non-3D/Non-3D.mm.json'
Path: /home/bkh/Downloads/into-cps-app-2.0.0-rc-linux-x64/case-study_three_tank/Multi-Models/Non-3D/Experiment 1/Non-3D.coe.json

The cosimulation engine (0.1.2) is running properly, and the Configuration section under Multi-Models->Non-3D is as I expect it (i.e. it does show the proper configuration). The consequence of the error above is also that I cannot simulate. Furthermore, the title of my experiment has been labelled as "INTO-CPS > undefined".

Am I doing something wrong?

Kind regards,

Tom Bokhove (Controllab)

**Comment by ldcouto** [comment]
Hi Tom,

With the current head of master, d9f60e4, for the three watertank, I don't have any issues with the config and I can run co-sims (Windows platform). Can you give me the hash that's causing you this failure?

Also, the error message shows up as red text inside the configuration box, right?

**Comment by Tom4444** [comment]
Hi Louis,

For the three-tank water example I used the revision with hash e5a92e7b95785a3f072783db02d5b6e659fc4f75 (which seems to be the one before Marcel made the commit of yesterday evening to fix the 3D animation FMU, and the one after you made the last commit to this example. As for the INTO-CPS app, I used the release candidate version of the app (2.0.0.0).

The error message does indeed show up in red text.

**Comment by Tom4444** [comment]
I took the head revision and build that one using the instructions on the corresponding page. The build went successful, but the result was the same, the same error as described in my initial post.

**Comment by ldcouto** [comment]
I'm sorry, built?

**Comment by Tom4444** [comment]
https://github.com/into-cps/intocps-ui section 'How to build'.

**Comment by ldcouto** [comment]
Ah, ok. That's what I was thinking.

You don't need to rebuild the app. Just stick to the RC. I was talking about the head of 3 watertanks: https://github.com/into-cps/case-study_three_tank/commit/d9f60e4954fcf0f2cc5765117b7e5a8a6b7ec684

Anyway, I am suspicious of the space in "Experiment 1". I will shortly push an update to the case study that removes it.

**Comment by ldcouto** [comment]
Alright, it's up. Please pull in the case study repo

**Comment by Tom4444** [comment]
I found the problem. It seems that the folder Multi-Models has two capital letters. The error however indicates that it cannot find a folder named Multi-models, which has a small-case letter m for models. If I fix this manually (rename the folder for me to Multi-models) the problem is resolved.

**Comment by ldcouto** [comment]
Ah yes, capitalisation. The bane of every multi-platform project. I will to go through all the projects and ensure that we are consistent with it.

Thanks for tracking this down Tom.

**Comment by ldcouto** [comment]
Closing this. See #153 for the follow-up.
