### ISSUE TITLE
Issues with file names examples

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#153]
The app assumes multi-model files are located in `Multi-models` (note lowercase m). This information is needed when constructing co-sim configs. 

Some examples have folder layouts with `Multi-Models` (note uppercase M). Great on windows, bad everywhere else (see #152).

Someone with a case-sensitive file system needs to go through all the examples and ensure they are properly capitalised. Afterwards, everyone should just delete their examples and re-clone (pulls with capitalisation changes are notoriously finicky).

At the same time, we should also remove any spaces from file names in the examples. The ability to deal with spaces in paths is inconsistent across the tool chain. Honestly, anyone who uses spaces in filenames, deserves whatever problem they get.

@richardpayne can you take care of this? For the record, every example should use `Multi-models`.

**Comment by richardpayne** [comment]
@ldcouto - no problem - I'll take this.

**Comment by richardpayne** [comment]
This has been addressed - all repositories have been updated
