### ISSUE TITLE
Can't return to simulation graph view

### ISSUE THREAD

**Issue by richardpayne** [into-cps/intocps-ui#156]
If I navigate away from the co-simulation graph in the app, I can't return to it - clicking on the experiment in the side bar brings me to a page to start simulation again. The COE server status window indicates the COE is still running.

**Comment by ldcouto** [comment]
Yeah, you're right. The Co-Sim view loads the page again.

I don't really want us to carry a lot of state inside the app to track ongoing co-sim graphs that people move away from. We can either send a warning message when the user moves away or open the graph in a new window instead (similar to COE status). What do you think @richardpayne ?

**Comment by richardpayne** [comment]
That's fair enough. Perhaps a new window would be useful (maybe with a timestamp to identify simulation results), this way a user could compare different co-sim setups side-by-side?

**Comment by ldcouto** [comment]
To be revisited after INTO-CPS
