### ISSUE TITLE
Closing the COE via app does not terminate Java process

### ISSUE THREAD

**Issue by richardpayne** [into-cps/intocps-ui#157]
When closing the COE in the app (by clicking the 'close' button) does not release port 8082. When trying to restart the COE I get the exception:

Couldn't start server:
java.net.BindException: Address already in use

See screenshot. The only way to get it running as far as I can tell is to restart my machine.

![screenshot 2016-09-09 14 47 46](https://cloud.githubusercontent.com/assets/5848867/18389191/b09c341a-769c-11e6-860a-cec2a8c12d7c.png)

**Comment by lausdahl** [comment]
This may happen if you have run a simulation where a Overture tool wrapper FMU crashed. The COE is dead but a child process running the shared memory for the tool wrapper (Overture) may still be present.

If on *nix check for a process that has "shm" in the name and kill it then it releases the COE process.
An update to the Overture FMU project will be released soon it should solve some of these issues.

**Comment by richardpayne** [comment]
I'll test that, thanks. Is there a similar process for Windows?

**Comment by swengaudk** [comment]
I'm not sure how this works on windows but it if it happens then you should have a java process you can kill, I would assume that it wither have COE or shmServer in the command line argument list.

for mac I used this to find and kill them: `ps aux | grep --color=never ShmServer | awk '{print \$2}' | xargs kill -9` but hopefully these should be a lot less likely to happen after we added timeout to most of the calls so it should eventually fail and exit. The current development version of Overture FMU should have these fixes. Repo + CLI http://overture.au.dk/into-cps/vdm-tool-wrapper/development/latest/

The CLI version can be run as: 

```bash
JAR=fmu-import-export-${VERSION}-jar-with-dependencies.jar
NAME="my-project"
MODEL=/source/to/VDM/model/root

java -jar $JAR -export --tool -name $NAME -root $MODEL -output .
```

**Comment by astefano** [comment]
Just to say that i have the same BindException on Windows. @richardpayne : instead of restarting the machine, you can run "resource monitor" to see the pid of the java procs listening to 8082 and then kill by running from cmd line: taskkill /F /PID <your_pid>

**Comment by ldcouto** [comment]
I've checked this again. The port is a symptom not the problem. When you "close" the COE via the app, it isn't actually closed at all. The COE java process keeps running. Regardless of whether a co-simulation was run.

I'll update the issue title accordingly.
