### ISSUE TITLE
Error in co-sim config when produced in Windows

### ISSUE THREAD

**Issue by richardpayne** [into-cps/intocps-ui#160]
When a co-sim config is defined in Windows (maybe edited too, not too sure), it can not be used in Mac. This error is shown:

Error: Could not parse config.
Message: Error: ENOENT: no such file or directory, open '/Users/nrjp6/Documents/Projects/INTO-CPS/INTO-CPS_Git/case-study_fcu/Multi-models\4-model\4-model.mm.json'
Path: /Users/nrjp6/Documents/Projects/INTO-CPS/INTO-CPS_Git/case-study_fcu/Multi-models/4-model-OM/Experiment_1/4-model.coe.json

Looking at the config itself, this is due to Windows using \\ in directory paths. Manually changing these to / resolves the problem. Using / works in Mac and Windows.

For example, changing the model.coe.json file from:

`{"startTime":0,"endTime":5000,"multimodel_path":"Multi-models\\4-model\\4-model.mm.json","livestream":{"{roomFMU}.room":["RAT"],"{environmentFMU}.env":["OAT_OUT","RAT_OUT"],"{controllerFMU}.controller":["valveOpen"],"{wallFMU}.wall":["lambdaOut"]},"algorithm":{"type":"fixed-step","size":1}}`

to 

`{"startTime":0,"endTime":5000,"multimodel_path":"Multi-models/4-model/4-model.mm.json","livestream":{"{roomFMU}.room":["RAT"],"{environmentFMU}.env":["OAT_OUT","RAT_OUT"],"{controllerFMU}.controller":["valveOpen"],"{wallFMU}.wall":["lambdaOut"]},"algorithm":{"type":"fixed-step","size":1}}`

resolves the issue.

**Comment by kgpierce** [comment]
Co-simulation configurations no longer point directly to files, so this has gone away.

**Comment by richardpayne** [comment]
Is this change made automatically to old confit files, or do we need to change existing cosim configurations manually?

Get Outlook for iOS<https://aka.ms/o0ukef>




On Thu, Oct 27, 2016 at 9:08 AM +0100, "Ken Pierce" <notifications@github.com<mailto:notifications@github.com>> wrote:


Co-simulation configurations no longer point directly to files, so this has gone away.

-

**Comment by CarlGamble** [comment]
Hi,

While editing papers this has sliped by me a bit.

So how do you locate the mm.json from the coe.json now (just to save me trauling through Kenneth’s emails)?


C
