### ISSUE TITLE
"Error in simulation" exception

### ISSUE THREAD

**Issue by richardpayne** [into-cps/intocps-ui#161]
Simulating the Smart Grid sg-blocks multi model (in development branch in SmartGrid Github repository), I get the following error: 

`ERROR [NanoHttpd Request Processor (#1)] (RequestProcessors.java:301) - Error in simulation
java.lang.NullPointerException`

The full COE log is below, I've no idea what the issue is. 

Overview
Console
COE(Command line options: [port]

Version: 0.1.2
Now running on port 8082
Server started, Hit Enter to stop.

{{H2}=file:////Users/nrjp6/Documents/Projects/INTO-CPS/INTO-CPS_Git/case-study_smart_grid/FMUs/House2.fmu, {H1}=file:////Users/nrjp6/Documents/Projects/INTO-CPS/INTO-CPS_Git/case-study_smart_grid/FMUs/House1.fmu, {PG}=file:////Users/nrjp6/Documents/Projects/INTO-CPS/INTO-CPS_Git/case-study_smart_grid/FMUs/PowerGeneration.fmu, {C}=file:////Users/nrjp6/Documents/Projects/INTO-CPS/INTO-CPS_Git/case-study_smart_grid/FMUs/SimplePulseSGController.fmu, {T3}=file:////Users/nrjp6/Documents/Projects/INTO-CPS/INTO-CPS_Git/case-study_smart_grid/FMUs/Transmission3.fmu, {SS}=file:////Users/nrjp6/Documents/Projects/INTO-CPS/INTO-CPS_Git/case-study_smart_grid/FMUs/Substation.fmu, {T1}=file:////Users/nrjp6/Documents/Projects/INTO-CPS/INTO-CPS_Git/case-study_smart_grid/FMUs/Transmission.fmu, {T2}=file:////Users/nrjp6/Documents/Projects/INTO-CPS/INTO-CPS_Git/case-study_smart_grid/FMUs/Transmission2.fmu}
[{H1}.h1.h_c -> {C}.c.h1_c, {H1}.h1.h_v -> {C}.c.h1_v, {H1}.h1.output -> {T2}.t2.input, {C}.c.h1p -> {H1}.h1.powerUsage, {C}.c.h2p -> {H2}.h2.powerUsage, {T2}.t2.output -> {H1}.h1.input, {T2}.t2.output1 -> {SS}.ss.plus1, {H2}.h2.h_c -> {C}.c.h2_c, {H2}.h2.h_v -> {C}.c.h2_v, {H2}.h2.output -> {T3}.t3.input, {T3}.t3.output -> {H2}.h2.input, {T3}.t3.output1 -> {SS}.ss.plus1, {PG}.pg.output -> {T1}.t1.plus, {T1}.t1.output -> {SS}.ss.input, {T1}.t1.output1 -> {PG}.pg.input, {SS}.ss.output -> {T2}.t2.plus, {SS}.ss.output1 -> {T3}.t3.plus, {SS}.ss.output2 -> {T1}.t1.input, {SS}.ss.currentOut -> {C}.c.ss_c, {SS}.ss.voltageOut -> {C}.c.ss_v]
[]
INFO [NanoHttpd Request Processor (#1)](CoeInitialize.scala:368) - OK c FMU: Called instantiate with instance c and guid {31e5ea39-927c-44c6-bdf5-e3f5b180b3be}
INFO [NanoHttpd Request Processor (#1)](CoeInitialize.scala:368) - OK c FMU: Launching Tool Wrapper memory key: '{31e5ea39-927c-44c6-bdf5-e3f5b180b3be}c' and resource location /var/folders/81/h98zll5j19vd408ntrg38rfn06153y/T/SimplePulseSGController2539086009441985026/resources/
INFO [NanoHttpd Request Processor (#1)](CoeInitialize.scala:368) - OK c FMU: Launching with shared memory key: '{31e5ea39-927c-44c6-bdf5-e3f5b180b3be}c'
New Apple shm key is: /2219735122952166369 from baseName /Local and name {31e5ea39-927c-44c6-bdf5-e3f5b180b3be}c
Starting IPC server with key: /2219735122952166369
New Apple shm key is: /14409356093532142033 from baseName /sig and name {31e5ea39-927c-44c6-bdf5-e3f5b180b3be}c
New Apple shm key is: /3923280890539857377 from baseName /sigAvail and name {31e5ea39-927c-44c6-bdf5-e3f5b180b3be}c
INFO [NanoHttpd Request Processor (#1)](CoeInitialize.scala:368) - OK c FMU: FMU Server client create, hosting SHM with raw key: {31e5ea39-927c-44c6-bdf5-e3f5b180b3be}c
Fork pid 626
Fork application java
Changed dir to: /var/folders/81/h98zll5j19vd408ntrg38rfn06153y/T/SimplePulseSGController2539086009441985026/resources/
java
-cp
*
org.crescendo.fmi.ShmServer
-p
{31e5ea39-927c-44c6-bdf5-e3f5b180b3be}c
Starting Crescendo ShmServer with key: '{31e5ea39-927c-44c6-bdf5-e3f5b180b3be}c'
DEBUG [main](SharedMemory.java:27) - Loading library: lib/Mac-x86_64/libsharedmemory.dylib
DEBUG [main](NativeLibraryLoader.java:38) - Extracting library from: lib/Mac-x86_64/libsharedmemory.dylib
DEBUG [main](NativeLibraryLoader.java:40) - Extracted library: /var/folders/81/h98zll5j19vd408ntrg38rfn06153y/T/jnifmuapi4728100766002880659/fmi-shm-Mac-x86_64/libsharedmemory.dylib
DEBUG [main](SharedMemory.java:32) - Loaded Library file: /var/folders/81/h98zll5j19vd408ntrg38rfn06153y/T/jnifmuapi4728100766002880659/fmi-shm-Mac-x86_64/libsharedmemory.dylib
Starting shared memory with key: {31e5ea39-927c-44c6-bdf5-e3f5b180b3be}c
{31e5ea39-927c-44c6-bdf5-e3f5b180b3be}c
Instantiating {31e5ea39-927c-44c6-bdf5-e3f5b180b3be}.c with loggingOn = true, resource location='file:/var/folders/81/h98zll5j19vd408ntrg38rfn06153y/T/SimplePulseSGController2539086009441985026/resources/'
Source root: /var/folders/81/h98zll5j19vd408ntrg38rfn06153y/T/SimplePulseSGController2539086009441985026/resources/model
Parsed 10 classes in 0.123 secs. 
No syntax errors

Type checked 12 classes in 0.093 secs. 
No type errors

ERROR [NanoHttpd Request Processor (#1)](RequestProcessors.java:301) - Error in simulation
java.lang.NullPointerException
at java.util.Vector.addAll(Vector.java:884)
at org.intocps.orchestration.coe.initializing.GraphUtil.findConnectionsInOrder(GraphUtil.java:108)
at org.intocps.orchestration.coe.BasicInitializer.checkRealAlgebraicCycles(BasicInitializer.java:352)
at org.intocps.orchestration.coe.BasicInitializer.initialize(BasicInitializer.java:107)
at org.intocps.orchestration.coe.scala.CoeSimulator$.simulate(CoeSimulator.scala:58)
at org.intocps.orchestration.coe.scala.Coe.simulate(Coe.scala:66)
at org.intocps.orchestration.coe.httpserver.RequestProcessors.processSimulate(RequestProcessors.java:297)
at org.intocps.orchestration.coe.httpserver.RequestHandler.simulate(RequestHandler.java:247)
at org.intocps.orchestration.coe.httpserver.RequestHandler.handleRequest(RequestHandler.java:183)
at org.intocps.orchestration.coe.httpserver.NanoWSDImpl.serveHttp(NanoWSDImpl.java:36)
at fi.iki.elonen.NanoWSD.serve(NanoWSD.java:861)
at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:925)
at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
at java.lang.Thread.run(Thread.java:745)

**Comment by ldcouto** [comment]
Hey @richardpayne 

I think we missed this issue completely. Is this still a problem or can I close?

**Comment by richardpayne** [comment]
I think it was due to a faulty model - I'll close it.
