### ISSUE TITLE
Ability to state platform compatibility for multi-models/projects

### ISSUE THREAD

**Issue by richardpayne** [into-cps/intocps-ui#162]
Some multi-models may not be co-simulated in some platforms due to: 
1. using 3D FMUs and  
2. issues with the FMUs themselves (e.g. line follower sensors don't work in Mac). 

Could this be indicated in any way (I know the app checks if FMUs are supported, but this doesn't fix the second case. Is there an way to manually specify platform compatibility?

**Comment by ldcouto** [comment]
To be revisited after INTO-CPS. This is definitely an important feature for the examples.

We could extend the multi-model config file to have such an entry I suppose. We could also try to detect the FMU compatibility by searching for the right binaries for each platform.

I suppose readme files or multi-model names can be used as some kind of indications as a workaround.
