### ISSUE TITLE
COE: Clearly indicate when a result no longer is reproducible from a given MultiModel+CoSim config using a different icon for the R_ folder in the project browser

### ISSUE THREAD

**Issue by lausdahl** [into-cps/intocps-ui#173]
Clearly indicate when a result no longer is reproducible from a given MultiModel+CoSim config using a different icon for the R_ folder in the project browser
-  Suggestion: use checksum of MM and coe config. This can then be compared the current MM and coe config

**Comment by ldcouto** [comment]
@lausdahl are we still working on this? The traceability task will cover some of this ground so I want to drop or at least archive the feature. What do you think?

**Comment by CThuleHansen** [comment]
This is definitely not dead. I know work has been done with checksums.

**Comment by ldcouto** [comment]
Alright, let's keep it going. But I think the traceability leads should be brought in the loop on this.
