### ISSUE TITLE
Ability to search (ctrl+f) in the app

### ISSUE THREAD

**Issue by HrNilsson** [into-cps/intocps-ui#178]
This is important for models with a lot of signals, where locating a specific signal is not simple.

**Comment by ldcouto** [comment]
Sorry for the late reply. Completely missed this issue.  Where do you want to do this searching?

**Comment by HrNilsson** [comment]
I imagine it will be useful throughout the app, but I especially missed it in the multi model simulation configuration where you choose which signals to plot.

**Comment by ldcouto** [comment]
I see your point. It could be a useful feature, for sure. I'm adding it to the list.

I know it's not ideal, but you can search and plot on the results.csv as a workaround. Have you considered this?

**Comment by ldcouto** [comment]
People at the plenary were mixed on this. We're archiving the enhancement to be revisited later.
