### ISSUE TITLE
Missing validation of FMU connections

### ISSUE THREAD

**Issue by HrNilsson** [into-cps/intocps-ui#179]
In a Multi-Model with a 20-sim FMU and a Overture FMU, it is not validated whether all inputs to the Overture FMU is connected or not.
Hence, it is possible to run a co-simulation where not all inputs are connected, resulting in odd outputs, without any warnings or errors.

**Comment by ldcouto** [comment]
What exactly do you want to check here? I have FMUs with unconnected inputs on purpose, very often. Is there way in FMI to mark an input as mandatory? Without that, I'm not sure it's good to try to "guess".

**Comment by HrNilsson** [comment]
I see your point, and I do not know if you can mark it mandatory. Maybe there is not a good way to check this. I just found it very frustrating, that it was so difficult to find the missing connections. 
In the app, when you make connections, you connect outputs to inputs. But in my case, with a number of unused outputs, and with all inputs mandatory, it would make much more sense to connect inputs to outputs. In this way it would be way easier to check that all the needed inputs have been connected. Especially if some outputs should be connected to multiple inputs.

**Comment by ldcouto** [comment]
I understand. The multi-model editing features of the app are meant to be a convenient way of editing multi-models but are not meant to be a full-fledged editor. Did you consider building a connections diagram in modelio?

**Comment by HrNilsson** [comment]
Yeah, I know that is the way to do it. I just figured, since you did make this convenient way, that I would bring you some feedback. And I think this would be a small but great enhancement.

**Comment by ldcouto** [comment]
It's good feedback and we're happy to have it. I was just trying to help solve your problem right now.

Do you think we should reverse the inputs and outputs columns?

**Comment by HrNilsson** [comment]
Thanks, and yes I would prefer that the inputs and outputs are reversed.
I think it is more intuitive and easier to use in that way.

**Comment by ldcouto** [comment]
I'm inclined to agree, although I'd like to get feedback from a few more users. I'll see if I can ask around at the plenary.

**Comment by ldcouto** [comment]
We did not exactly conduct a scientific survey but there seems to be interest in this from some of the project partners. I'm adding it as an enhancement.

**Comment by ldcouto** [comment]
People at the plenary were mixed on this. Archiving the enhancement so it can be revisited later.
