### ISSUE TITLE
Default parameters generation

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#18]
From within modelio, when generating the connections mapping, set the initial values of the FMU scalar variables. 
* For user set variables, use thoses values. 
* For any other variables, use zero or zero-equivalents.

**Comment by etiennebrosse** [comment]
This is the behavior implemented in the 1.0.28 version of the INTO-CPS extension but only Real Attribut have been tested. 
What is the case for Boolean, String and Enumeration?

**Comment by ldcouto** [comment]
For Boolean and string, I guess it's false and "". No idea about enumeration.

@lausdahl , does the COE consider any kinds of defaults?

**Comment by lausdahl** [comment]
I'm not sure I understand what this issue is about. If we are talking about setting the initial values and parameters of FMU scalar variables, then you should leave them unset unless a desired value is desired. The reason for this is that the parameters the COE sets is an override of what the individual FMUs contain in their `modelDescription.xml`

The COE does not support enumerations, and I never tried using strings. I think the COE supports strings but none of the simulators does I think.

**Comment by ldcouto** [comment]
Yeah, it's the FMU scalars. Are you saying the COE already uses defaults when the variable is unset?

**Comment by lausdahl** [comment]
The COE follows the standard and uses start values for the scalar variables if defined (and allowed). If you specify additional parameters in the APP then these values override these start values.

**Comment by etiennebrosse** [comment]
Right now, the SysML Model has the start values for each scalar variable it does not make sense to add them in the generated configuration, am I right? If the user want to override these values  when do we give it this possibility? During the Configuration generation? Under the App? or both?
I would say both. Do you agree on this?

**Comment by lausdahl** [comment]
The start values should not be configurable in general, but I agree that we should be able to set them for parameters in the exported configuration from Modelio to the app.

all other start values should be set when exporting the modelDescription.xml and then the tool that imports them can chose to use these on export.

**Comment by etiennebrosse** [comment]
I guess that we are on the same page here. Thanks

**Comment by ldcouto** [comment]
Etienne, what's the status here? Can I close this issue?

**Comment by CThuleHansen** [comment]
Yes :)
