### ISSUE TITLE
Downloading examples to non-default location does not open example automatically

### ISSUE THREAD

**Issue by kgpierce** [into-cps/intocps-ui#180]
When downloading examples through the App, if you change the "Project root path" to something other than the default, then the example is not opened automatically. If "default_projects_folder_path" and "Project root path" match then it is opened.

**Comment by ldcouto** [comment]
Hi Ken,

Sorry for not responding sooner. This fell through the cracks. I just tried to import an example to another location and the project opened successfully. Would you mind testing this again with the latest version of the app? If it's still a problem, we will try to reproduce it on my machine.

**Comment by ldcouto** [comment]
I'm closing this. Reopen if it's still a problem.
