### ISSUE TITLE
INTO-CPS Release 2.1.5 win32 ia32 broken

### ISSUE THREAD

**Issue by lausdahl** [into-cps/intocps-ui#182]
The win32 release does not work at all. It loads with a bland screen and if the console it opened then this error is shown:

`module.js:440 Uncaught Error: Cannot find module './IntoCpsAppEvents'`

This makes it difficult to test the app in virtual machines since x64 win VM use a lot of resources. We use the win32 for testing at AU when needed.

**Comment by lausdahl** [comment]
Version: `2.1.6.dev-win32-ai32` works

**Comment by ldcouto** [comment]
Let's test this in the RC before closing the issue.

**Comment by ldcouto** [comment]
Successfully tested by @lausdahl 

Closing.
