### ISSUE TITLE
Cannot Report an Issue

### ISSUE THREAD

**Issue by evidals** [into-cps/intocps-ui#183]
when: Help> Report issue
IntoCPS application pop ups a window trying to login to your GitHub account but this never happens.

**Comment by ldcouto** [comment]
Thanks for reporting this @evidals . We cannot reproduce the issue though. The GitHub page can be quite slow to appear. Have you waited long for it?

Another possibility is if you are behind a proxy - at the moment, the app does not fully support proxy connections.

**Comment by ldcouto** [comment]
Hi again,

Have you had a chance to retry this?

**Comment by evidals** [comment]
It works fine in both 2.1.5 and 2.1.8

Regards,

Enrique

2017-01-05 17:50 GMT-05:00 <evidals@pucp.edu.pe>:

**Comment by ldcouto** [comment]
Great. Thank you for checking again.
