### ISSUE TITLE
JavaScript Error when reload the view

### ISSUE THREAD

**Issue by evidals** [into-cps/intocps-ui#184]
when: you reload the view (view>reload) and if you have another window open ( settings, COE server, download manager or FMU builder), then if you try to close this window, appears:

A javaScript error occurred in the main process
Uncaught Exception:
Error: Attempiting to call a function in a renderer window that has been closes or released.
Function provided here: DialogHandler.openWindow
(D:\pathtointocps-app\resources\APP...:18)
at BrowserWindow.callIntoRenderer
(D:\pathtointocps-app\resources\APP...:19)
at emitOne (event.js:101:20)
at BrowserWindow.emit(event.js:188:7)

**Comment by ldcouto** [comment]
Confirmed.

@CThuleHansen , I think this is similar to #126. I'd be happy with closing any dependent windows when we reload.
