### ISSUE TITLE
Handle empty project directories for Git

### ISSUE THREAD

**Issue by FlorianLapschies** [into-cps/intocps-ui#187]
Since Git does not track directories, empty directories get lost when using Git. This also means that some activities like DSE, MC, TDG might be missing in the project browser because they depend on the existence of the respective directory.
Proposed solution: Add an empty .missing file during project creation to give Git something to track.

**Comment by ldcouto** [comment]
The app will now create .gitignore files for every folder. 

We will have to go through the examples manually to add the .gitignore files to them.

**Comment by ldcouto** [comment]
Actually, I've changed the import feature so that it now creates the folders after importing. So, no updates should be needed for the examples.
