### ISSUE TITLE
Linux: Insufficient number of inotify watchers

### ISSUE THREAD

**Issue by FlorianLapschies** [into-cps/intocps-ui#189]
Under Linux each folder that is displayed in the project browser is watched by inotify in order to update the browser when files are added/deleted. The maximum number of watchers per user is a kernel setting that is exposed by the file /proc/sys/fs/inotify/max_user_watches and can be increased when needed. As it turns out there are situations where the default limit is not sufficient and items are then missing from the browser.
The watchers are dynamically released by the application. It should be investigated whether this is done properly. Another cause might be that other programs depleted this resource.

**Comment by ldcouto** [comment]
Hey Florian,

I think you guys are the only ones developing on Linux. Are you looking into this?

**Comment by FlorianLapschies** [comment]
Hi Luis, so far this problem occurred only once to me and I did not investigate any further.

**Comment by ldcouto** [comment]
Alright, let's keep it an eye on it for now. I'll revisit this in a couple of months.

**Comment by FlorianLapschies** [comment]
I am now pretty sure that the problem is caused by Visual Studio Code. Running two Instances of Visual Studio Code without running the INTO CPS application depletes all available per user watches.
This can be verified by running "tail -f <SOME-FILE>" which then reports:
```
tail: inotify resources exhausted
tail: inotify cannot be used, reverting to polling
```

**Comment by FlorianLapschies** [comment]
Note, that this issue is also mentioned on the [Running VS Code on Linux](https://code.visualstudio.com/docs/setup/linux#_common-questions) page.

**Comment by ldcouto** [comment]
Good find. Thanks for looking into it.
