### ISSUE TITLE
COE: Could not parse config.

### ISSUE THREAD

**Issue by lausdahl** [into-cps/intocps-ui#190]
This happens if any of the FMU files are removed from the system
```
Error: Could not parse config.
Message: Error: ENOENT: no such file or directory, lstat 'C:\Users\IEUser\into-cps-projects\case-study_single_watertank\FMUs\C:\Users\IEUser\Downloads\string-in.fmu'
Path: C:\Users\IEUser\into-cps-projects\case-study_single_watertank\Multi-models\stringmix-Cin\mm.json
```

**Comment by lausdahl** [comment]
why was this first closed then reopened? the commit is in master?

**Comment by CThuleHansen** [comment]
Because of jenkins build failure that was actually not caused by this commit. But reverted immediately to attempt to fix it fast, with no luck, because it was something else.
But it is closed now :)
