### ISSUE TITLE
[case-study_line_follower_robot] [coe] [windows 7]

### ISSUE THREAD

**Issue by astefano** [into-cps/intocps-ui#193]
Hi again,

Just for info, i've just tried simulating the follower example with coe on windows (cygwin). At the command `curl -s -H "Content-Type: application/json" --data @config.json http://localhost:8082/initialize/$sessionId` i get:

`$ java -jar coe.jar
COE(Command line options: [port]

Version: 0.1.10
Now running on port 8082
Jan 05, 2017 9:41:42 AM fi.iki.elonen.NanoHTTPD$ClientHandler run
SEVERE: Communication with the client broken, or an bug in the handler code
java.lang.NullPointerException
        at org.intocps.orchestration.coe.httpserver.RequestProcessors.processInitialize(RequestProcessors.java:120)
        at org.intocps.orchestration.coe.httpserver.RequestHandler.initialize(RequestHandler.java:316)
        at org.intocps.orchestration.coe.httpserver.RequestHandler.handleRequest(RequestHandler.java:175)
        at org.intocps.orchestration.coe.httpserver.NanoWSDImpl.serveHttp(NanoWSDImpl.java:36)
        at fi.iki.elonen.NanoWSD.serve(NanoWSD.java:861)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:925)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Unknown Source)` 

Cheers,
Lacramioara

PS
The case-study_three_tank works fine.

**Comment by ldcouto** [comment]
That is not a very informative stack trace. @lausdahl , any thoughts what could be causing this?

@astefano , can you please post the config.json file?

**Comment by astefano** [comment]
the config file is in the zip
[config.zip](https://github.com/into-cps/intocps-ui/files/687997/config.zip)

(it is the one generated by "create co-simulation configuration" from into-cps-app-2.1.8.exe after importing the case study; i found it in `into-cps-projects\case-study_line_follower_robot\Multi-models\lfr-3d\co-sim-72\R_1-4-2017_12-00-16_PM`)

**Comment by ldcouto** [comment]
Seems right, at a glance. Let's wait for @lausdahl

**Comment by lausdahl** [comment]
It looks like either forgot to create the session before initialising or that the post data was not received.

**Comment by ldcouto** [comment]
So, can I close this?

**Comment by lausdahl** [comment]
I dont think I can do anything more with this as is

**Comment by ldcouto** [comment]
Alright. I am closing this. @astefano , please reopen or don't hesitate to create a new issue if you are still experiencing problems.

**Comment by astefano** [comment]
Hi,

i tried to redo my experiments with coe but i'm stuck. I tried both instructions, from the manual D4.2 and from the webpage http://into-cps.github.io/simulation/example.html. I'm on Windows 7 and run the commands from cygwin. First, i start coe with `java -jar coe.jar`. I get:
```$ java -jar coe.jar
Version: 0.2.3-SNAPSHOT
Now running on port 8082```

Then:
A. From the manual:
1. run `$curl http://localhost:8082/createSession`
i get a sessionId:
`{"sessionId":"39c82e21-fc70-44f9-9454-726f4ecb1fab"}`
2. run `curl -H "Content-Type: application/json" --data @conf.json http://localhost:8082/initialize/sessionID`
i get: 
`Warning: Couldn't read data from file "conf.json", this makes an empty POST. Missing session`

B. from the webpage:
1. run ```sessionIdJson=$(curl -s http://localhost:8082/createSession)
2. run sessionId=`echo $sessionIdJson | cut -d ":" -f 2- | cut -d "}" -f 1` ```
3. run `curl -s -H "Content-Type: application/json" --data @config.json`
i get `http://localhost:8082/initialize/$sessionId Missing session`
But now in the terminal with the coe i also get:
```Apr 03, 2017 12:36:05 PM fi.iki.elonen.NanoHTTPD$Response send
SEVERE: Could not send response to the client
java.net.SocketException: Software caused connection abort: socket write error
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(Unknown Source)
        at java.net.SocketOutputStream.write(Unknown Source)
        at fi.iki.elonen.NanoHTTPD$Response.sendBody(NanoHTTPD.java:1620)
        at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1593)
        at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1583)
        at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1550)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:960)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Unknown Source)```

Any clue what might be wrong? The config file i'm using is the one from the into-cps-projects\case-study_three_tank\Multi-models\Non-3D\Experiment1\R_1-4-2017_12-26-52_PM

Puzzled,
lacramioara

**Comment by ldcouto** [comment]
The manual is updated more frequently.

The error from the first case means you do not have a file called `conf.json`

For the second, when you run the `createSession` do you get a reply with a number from the COE? It seems like the session is not being properly created.

Can you try running the COE on regular command line instead of cygwin?

**Comment by astefano** [comment]
Hi Luis,

Yes, my bad, didn't pay attention the file is named config.json and not conf.json. Ok, so now that i corrected this, in both scenarios i get the `socket write error`. 
Yes, `createSession` returns a sessionId:

`astefanoaei@fortiss-n-019 ~/coe/R_1-4-2017_12-26-52_PM`
`$ curl http://localhost:8082/createSession`
`{"sessionId":"2e4251ad-113c-48c1-b0fb-b10ff63e8547"}`

I've just tried running COE on regular cmd line and i get instead:
`C:\Users\astefanoaei\home\coe\R_1-4-2017_12-26-52_PM>curl -H "Content-Type: application/json" --data @config.json http://localhost:8082/initialize/sessionID`
`curl: (6) Couldn't resolve host 'fmus:tank1:file'`
`curl: (6) Couldn't resolve host 'fmus:tank2:file'`
`curl: (3) [globbing] bad range specification in column 47`
`curl: (3) [globbing] bad range specification in column 33`
`curl: (3) [globbing] bad range specification in column 40`
`curl: (6) Couldn't resolve host 'parameters:controller.controller.wt3_max'`
`curl: (6) Couldn't resolve host 'parameters:controller.controller.wt3_min'`
`curl: (3) [globbing] bad range in column 30`
`curl: (3) [globbing] bad range in column 40`
`curl: (3) [globbing] bad range in column 30`
`curl: (6) Couldn't resolve host 'algorithm:type'`
`curl: (6) Couldn't resolve host 'algorithm:size'`
`Missing session`

In the cmd line window where COE runs i get the same `socket write error`.

Any clue why?

Thanks again,
lacramioara

**Comment by ldcouto** [comment]
From the look of it, the json file isn't being processed correctly. Curl is trying to read the connection point from the json file.

Can you please repost the config.json file. Also, make sure your `sessionID ` variable is correct (you can use echo to view it)

**Comment by astefano** [comment]
Hi,

Ok, so i finally understood i need to set the sessionId var myself... 

Now, at command prompt i get: 

`C:\Users\astefanoaei\home\coe\R_3-31-2017_4-41-56_PM>curl http://localhost:8082/
createSession`
`{"sessionId":"2ba00323-6ccd-4260-9cb1-e52130351717"}`

`C:\Users\astefanoaei\home\coe\R_3-31-2017_4-41-56_PM>set sessionId=2ba00323-6ccd
-4260-9cb1-e52130351717`

`C:\Users\astefanoaei\home\coe\R_3-31-2017_4-41-56_PM>curl -H "Content-Type: appl
ication/json" --data @config.json http://localhost:8082/initialize/%sessionId%`
`curl: (6) Couldn't resolve host 'fmus:Controller:file'`
`curl: (3) [globbing] bad range specification in column 34`
`curl: (3) [globbing] bad range specification in column 37`
`curl: (6) Couldn't resolve host 'parameters:Controller.cont.maxlevel'`
`curl: (6) Couldn't resolve host 'parameters:Controller.cont.minlevel'`
`curl: (3) [globbing] bad range in column 34`
`curl: (3) [globbing] bad range in column 31`
`curl: (6) Couldn't resolve host 'algorithm:type'`
`curl: (6) Couldn't resolve host 'algorithm:size'`
`Unrecognized token 'fmus': was expecting 'null', 'true', 'false' or NaN`
` at [Source: fmus:{WaterTank}:file:///C:/Users/astefanoaei/into-cps-projects/case-study_single_watertank/FMUs/singlewatertank-20sim.fmu; line: 1, column: 5]`

`C:\Users\astefanoaei\home\coe\R_3-31-2017_4-41-56_PM>curl -H "Content-Type: application/json" --data @config.json http://localhost:8082/simulate/%sessionId%`
`curl: (6) Couldn't resolve host 'fmus:Controller:file'`
`curl: (3) [globbing] bad range specification in column 34`
`curl: (3) [globbing] bad range specification in column 37`
`curl: (6) Couldn't resolve host 'parameters:Controller.cont.maxlevel'`
`curl: (6) Couldn't resolve host 'parameters:Controller.cont.minlevel'`
`curl: (3) [globbing] bad range in column 34`
`curl: (3) [globbing] bad range in column 31`
`curl: (6) Couldn't resolve host 'algorithm:type'`
`curl: (6) Couldn't resolve host 'algorithm:size'`
`SERVER INTERNAL ERROR: Serve() returned a null response.`

so there's a problem at initialisation and simulation. Consequently, i don't get any results. The log file for the coe is attached. 

With cygwin, the initialisation and the simulation seem to pass but the results show just 1 step (see snapshot attached, res_cygwin.png
[logs_config_res.zip](https://github.com/into-cps/intocps-ui/files/895850/logs_config_res.zip)
).

`astefanoaei@fortiss-n-019 ~/coe/R_3-31-2017_4-41-56_PM$ curl http://localhost:8082/createSession`                                                                                                                                                                                                                           `{"sessionId":"a3908ce9-7594-4ea2-b574-9cad4ba0953d"}`
`astefanoaei@fortiss-n-019 ~/coe/R_3-31-2017_4-41-56_PM$ sessionId=a3908ce9-7594-4ea2-b574-9cad4ba0953d`

`astefanoaei@fortiss-n-019 ~/coe/R_3-31-2017_4-41-56_PM$ curl -H "Content-Type: application/json" --data @config.json http://localhost:8082/initialize/$sessionId`
`[{"status":"Initialized","sessionId":"a3908ce9-7594-4ea2-b574-9cad4ba0953d","lastExecTime":0,"avaliableLogLevels":{"{Controller}.cont":[{"name":"logAll","description":null},{"name":"logError","description":null},{"name":"logFmiCall","description":null},{"name":"Protocol","description":null},"name":"VdmOut","description":null},{"name":"VdmErr","description":null}],"{WaterTank}.wt":[]}}]`
`astefanoaei@fortiss-n-019 ~/coe/R_3-31-2017_4-41-56_PM$ curl -H "Content-Type: application/json" --data @config.json http://localhost:8082/simulate/$sessionId`
`{"status":"Finished","sessionId":"a3908ce9-7594-4ea2-b574-9cad4ba0953d","lastExecTime":1068}`
 
The corresponding log is also attached. 

Both logs suggest coe doesn't find Overture ("Make sure the execution tool: 'Overture' is available during this simulation."). 

Could this be the reason why the 1 step execution in the result? But Overture is on my path... Where does coe look for Overture? And how come into-cps-app-3.0.0.exe produces the right simulation? 

A few more questions:
- why does the behaviour of coe differ so much between running it within command prompt or within cygwin? 
- which one should i use? 

Puzzled,
Lacramioara

**Comment by ldcouto** [comment]
Hi,

Sorry you are struggling with this. Let's see if we can keep troubleshooting.

The first example is still not reading the configuration properly. If you look at ` curl: (6) Couldn't resolve host 'fmus:Controller:file' `, curl thinks the content of the json file is a URL. Obviously it's not.

The length of the simulation is configured in a json payload. Ex: `{"startTime":0,"endTime":1200,"logLevels":{}}`

The message about Overture is just informative -- it has to do with the FMI and the type of FMU. But in fact, Overture is embedded inside the FMU so that is not a problem.

The difference of behaviour in the COE is most likely due to differences in your environments. The curl versions may also be different. I don't have any experience with using the COE on Cygwin, so I cannot comment on  -- I personally use git-bash. I would recommend that you use the regular CLI, just so it's a more standard environment and we can more easily replicate your issues.

**Comment by astefano** [comment]
Thanks a lot Luis, i understand now that the simulation takes a json file different from the initialisation. 
Great, this solves my problem, i get what i want. Now let's try the distributed version :).

Please feel free to close this "issue".

Thanks again,
l

PS
There's a typo in the manual, pg 34 in D4.2, the command:
`curl -H "Content-Type: application/json" --data @coeconf.json http://localhost:8082/simulate/sessionID`
should be
`curl -H "Content-Type: application/json" --data @startend.json http://localhost:8082/simulate/sessionID`
that confused me, i thought it's the same json file for both initialisation & simulation.

**Comment by ldcouto** [comment]
Great to hear you are sorted. Good luck with the distributed stuff -- feel free to open another issue if you need help with that.

Thanks for spotting the typo in the manual. We'll take care of it.
