### ISSUE TITLE
can not acces to the interactive list of bugfixes of coe

### ISSUE THREAD

**Issue by evidals** [into-cps/intocps-ui#194]
if you try to access to the interactive list by the intoCPS App Download Manager > Co-simulation Orchestration Engine - Co-simulation Orchestration Engine (0.1.10) **Release Page**  

Result by clic show you: 404 This is not the web page you are looking for .

Please Update

**Comment by ldcouto** [comment]
The COE tracker is private. Do you have access to it?

**Comment by evidals** [comment]
No I´ve not.

**Comment by evidals** [comment]
Maybe you can show explicity that the access is not public at the beginning

**Comment by ldcouto** [comment]
You are very right.

@CThuleHansen , can you please edit the COE release notes? Either remove the phrase about the interactive bug list or add a note saying that it's private.

**Comment by CThuleHansen** [comment]
Fixed with the text: 

> Links require the private repository.
