### ISSUE TITLE
Just 1 Progress Bar shows all files download

### ISSUE THREAD

**Issue by evidals** [into-cps/intocps-ui#195]
When you download more than one file in the intoCPS Download Manager
All the download progress is shown in just one progress Bar and it looks a little messy.

Maybe you can show a new progress bar after clic in the download link. 

Regards,

Enrique

**Comment by ldcouto** [comment]
Interesting idea. I've never downloaded more than 1 tool at a time.

@CThuleHansen can you give an idea of how much effort this would take?

**Comment by CThuleHansen** [comment]
I have no idea. Should be doable within reasonable amounts of time. Maybe a day

**Comment by ldcouto** [comment]
Alright, let's try to carry it
