### ISSUE TITLE
App crashes on mac when quit is invoked

### ISSUE THREAD

**Issue by CThuleHansen** [into-cps/intocps-ui#197]
This is due to our choice of creating the menu in a renderer process.
The renderer process is closed before the quit event, which is implemented in the just closed renderer process. Therefore the object containing the quit functionality has been destroyed -> exception.

Fix: Close app when all windows are closed on mac as well, even though this is not default behaviour.

**Comment by lausdahl** [comment]
![image](https://cloud.githubusercontent.com/assets/2575418/21802121/d4e7a26c-d724-11e6-8391-69e61c17ec52.png)
