### ISSUE TITLE
no link for Overture C Code generator plugin in release 0.0.11

### ISSUE THREAD

**Issue by evidals** [into-cps/intocps-ui#199]
I´ve a doubt: 
Why is no longer the link for:  **Overture C Code Generator Plugin - The C Code Generator Plugin for Overture** in: 
into-CPS Download Manager -> Overview - Release: 0.0.11  ?

Regards,

Enrique

**Comment by lausdahl** [comment]
The Overture C Code Generator Plugin is part of Overture and available through the update sites in Overture.

Alternatively you can install "Overture FMU Import / Exporter - Overture FMI Support" from the update manager which also inclides the C code generator.
