### ISSUE TITLE
Crash with "Enable All log categories per instance"

### ISSUE THREAD

**Issue by gmeisl-twt** [into-cps/intocps-ui#202]
When I run a co-simulation with Matlab-based source-code FMUs, the COE Server crashes (see attached logs).
[Log&json Files.zip](https://github.com/into-cps/intocps-ui/files/725938/Log.json.Files.zip)

Nachtrag: Sorry, einen wichtigen Hinweis habe ich vergessen. Das Problem tritt auf sobald die Option "Enable All log categories per instance" aktiviert wird.

**Comment by ldcouto** [comment]
Just to be certain, can you confirm that this exact same configuration runs with reduced logging?

**Comment by gmeisl-twt** [comment]
Hi Luis,

yes I can switch between working/error by changing this one tick.

Best regards

Gerd



Von:    Luis Diogo Couto <notifications@github.com>
An:     into-cps/intocps-ui <intocps-ui@noreply.github.com>
Kopie:  gmeisl-twt <gerd.meisl@twt-gmbh.de>, Author 
<author@noreply.github.com>
Datum:  30.01.2017 10:58
Betreff:        Re: [into-cps/intocps-ui] Crash with "Enable All log 
categories per instance" (#202)



Just to be certain, can you confirm that this exact same configuration 
runs with reduced logging?

**Comment by ldcouto** [comment]
Thanks. Can you share these FMUs within INTO-CPS?

**Comment by gmeisl-twt** [comment]
Unfortunately the FMUs contain the source code which I am not allowed to 
share. 
There may be ways to circumvent this problem but only with some effort. Do 
you think the available error messages may be sufficient to solve the 
problem? I can also offer you to do further tests or a screen-sharing 
session, it this would help. 
If you really need the FMUs I have to talk to my boss and discuss whether 
we can make this possible.

Cheers

Gerd



Von:    Luis Diogo Couto <notifications@github.com>
An:     into-cps/intocps-ui <intocps-ui@noreply.github.com>
Kopie:  gmeisl-twt <gerd.meisl@twt-gmbh.de>, Author 
<author@noreply.github.com>
Datum:  30.01.2017 17:00
Betreff:        Re: [into-cps/intocps-ui] Crash with "Enable All log 
categories per instance" (#202)



Thanks. Can you share these FMUs within INTO-CPS?

**Comment by ldcouto** [comment]
Yeah I'm familiar with those difficulties, from our own FMUs.

@lausdahl , can you take a look at these logs and see if they are enough for you to debug it?

**Comment by lausdahl** [comment]
Hi please check the implementation of the FMU. The crash is happening inside the FMU so the COE is most likely unable to do anything about this:

```
Stack: [0x000000001ee70000,0x000000001ef70000],  sp=0x000000001ef6e2b8,  free space=1016k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [msvcrt.dll+0x15888]
C  [OLEAUT32.dll+0x7f88]
C  [OLEAUT32.dll+0x8dba]
C  [OLEAUT32.dll+0x8d7d]
C  [ArtSimFMU.dll+0x213c2]
C  [ArtSimFMU.dll+0x20885]
C  [ArtSimFMU.dll+0x23380]
C  [ArtSimFMU.dll+0x36cbb]   <--- this must be fmi2SetDebugLogging(...)
C  [fmuapi.dll+0x15ef]
C  0x0000000002a37f74

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.intocps.fmi.jnifmuapi.NativeFmuComponent.nSetDebugLogging(JJZ[Ljava/lang/String;)B+0
j  org.intocps.fmi.jnifmuapi.FmuComponent.setDebugLogging(Z[Ljava/lang/String;)Lorg/intocps/fmi/Fmi2Status;+15
```

I would suggest to re-compile the FMU with debugging symbols and log what is send received in:

```C
 fmi2Status fmi2SetDebugLogging(fmi2Component c, fmi2Boolean loggingOn, size_t nCategories,
		const fmi2String categories[])
```

**Comment by gmeisl-twt** [comment]
After a hint by Kenneth we found an error in our FMU. 
So there only remains the question whether the error message can be adapted, so that it becomes apparent when a COE-crash is caused by an erroneous FMU?

Thanks
Gerd

**Comment by ldcouto** [comment]
Not sure. @lausdahl , is this feasible?

**Comment by lausdahl** [comment]
We cannot do much since it crashes in C destroying the complete program so we have no way to report anything.

**Comment by ldcouto** [comment]
Alright, thanks. Closing this.

Still a good limitation of FMI to have captured.
