### ISSUE TITLE
Cannot change from Co-Sim COnfigurationView

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#203]
If we open a co-sim config view, it becomes impossible to open any other view-model, then open a co-sim configuration, it is no longer possible to open another view, such as multi-model or dse.

The title changes at the top but the main view is always cosim (see attached).

Bizarrely, this error only occurs in the `npm start` version of the app. The packaged one works fine. But I'm worried that there is something wrong inside the app and it's just a matter of time till it hits us.

**Comment by lausdahl** [comment]
This cannot be reproduced neither by @CThuleHansen or me

**Comment by ldcouto** [comment]
Really? I can do it on the current master.

![untitled](https://cloud.githubusercontent.com/assets/582801/22687950/0aeeca6c-ed22-11e6-82ba-c1426a7feb8d.png)

What version of npm/node are you guys running?
I am on 3.10.6/4.4.6

Also, Kenneth, please stop creating labels for one-time use :P 

Makes my job a mess.

**Comment by lausdahl** [comment]
The label was not just for this one we have more issues which we cannot reproduce.

node: v7.4.0
npm: 4.0.5

**Comment by ldcouto** [comment]
There's no more bugs with the label and, in any case, I am in charge of triaging bugs.

By the way, you are not the only devs. I can produce this error so the label isn't accurate anyway.

I'll test at home with other versions and check this further.

**Comment by CThuleHansen** [comment]
Just tried again on master with rm –rf node_modules, rm-rf typings, rm –rf dist, npm install, gulp init, gulp build, npm start
and I cannot reproduce it.
Can you give me the exact steps you are executing?
Npm version: 4.0.2
Node version: 6.9.4

**Comment by ldcouto** [comment]
Sure. I also did the full rebuild (rm -rf node_modules, etc.)

After the rebuild and launching with npm start...

1. create new project
2. create multi-model
3. create config (view switches automatically)
4. click on multi-model - title changes but main view remains (as in screenshot).

I'll check with node 7 at home and see from there. I am willing to believe this is some weird behaviour in node 4 or my laptop. Can we get a third person to try this?

**Comment by CThuleHansen** [comment]
Yes I also have this

**Comment by ldcouto** [comment]
I know. I meant a third beyond you and Kenneth. So, I guess a fourth :P

I think @idhugo is working on the app too now so he should be able to try

**Comment by CThuleHansen** [comment]
I am experiencing it too @ldcouto .

**Comment by ldcouto** [comment]
Ah, ok. Sorry, I got confused cause of what Kenneth said initially

**Comment by ldcouto** [comment]
Tested at home on the mac. Same behavior.

```
$ npm -v
4.0.5
$ node -v
v7.4.0
```

**Comment by CThuleHansen** [comment]
This issue is really difficult to fix without proper debugging

**Comment by ldcouto** [comment]
Yeah. I've created #223 for that

**Comment by ldcouto** [comment]
#223 is fixed. Sadly, this error is still occurring. Uglify was not the problem.

**Comment by CThuleHansen** [comment]
I have found the problem and fixed it in a local branch. Attempting to create a better solution for hte long run.. It is because some angular stuff created by rasmus silences errors.. Really annoying, took all today
