### ISSUE TITLE
Improved warnings for MM config

### ISSUE THREAD

**Issue by bandurvp** [into-cps/intocps-ui#204]
These warnings come from unconnected / incorrectly named variables in the modelDescription.xml file. @CThuleHansen 

![mmconfig-warnings](https://cloud.githubusercontent.com/assets/7499001/22327364/17fe56ba-e3b7-11e6-95c5-a66457475a58.png)

**Comment by CThuleHansen** [comment]
Improve this by adding FMU and instance name to the warning text.

**Comment by ldcouto** [comment]
Will you be working on this @CThuleHansen or should I archive it?

**Comment by CThuleHansen** [comment]
@ldcouto if I have time.. It is definitely only nice to have

**Comment by ldcouto** [comment]
We'll give it a couple of releases. If no progress, I'll archive it. Just to keep it tidy :)
