### ISSUE TITLE
Missing app version

### ISSUE THREAD

**Issue by CThuleHansen** [into-cps/intocps-ui#205]
Because of the new traceability stuff we need a way to get the version of the app inside the app.
@ldcouto are you up for this?

**Comment by ldcouto** [comment]
Electron does this. The following snippet returns the version as specified in package.json.
```typescript
import { IntoCpsApp } from "./IntoCpsApp";

/// ...

1b6d0b6b8b0c.png)
IntoCpsApp.getInstance().app.getVersion();
```
 
**Important Note:**
The value is read from package.json. It will not work properly if you launch the app with npm start -- it returns the electron version instead.

It works for the packaged app fine. For development mode, you can launch the app with ` ./node_modules/.bin/electron . ` and it will also work.

**Comment by CThuleHansen** [comment]
Great, thanks!
