### ISSUE TITLE
Cannot find module './IntoCpsAppEvents'

### ISSUE THREAD

**Issue by cfjkoenig** [into-cps/intocps-ui#211]
I unpacked the .zip file of the 2.1.10 RC (Win64), start the app, and an error is shown in the console, saying "uncaught error: Cannot find module './IntoCpsAppEvents' module.js:440.

However, the file "IntoCpsAppEvents.js" exists in the folder \resources\app.

This prevents the whole app from starting.

**Comment by CThuleHansen** [comment]
Hi @cfjkoenig, just to clarify some stuff.

Does this happen immediately after opening the app without clicking anything?
Do you have a project loaded?

Please provide the entire log message.

I have just run this: into-cps-app-2.1.10-rc-win32-x64.zip and I am not experiencing the issue that you are reporting.

**Comment by cfjkoenig** [comment]
After a fresh download of the .zip file and unpacking it, the error disappeared. Closing the issue
