### ISSUE TITLE
Invalid Modelo-Open download

### ISSUE THREAD

**Issue by avh-agrointelli** [into-cps/intocps-ui#212]
In the INTO-CPS Application 2.1.8, the Modelio - UML/BPMN modelling tool (3.4.1) download is invalid (the compressed zipped folder cannot be opened)

**Comment by CThuleHansen** [comment]
I am getting this too. It is because of a bad MD5 `hash: internal/process/next_tick.js:103 Uncaught (in promise) Bad MD5 expected: '180c744b0bffd064dc349b1035ccb1ca' got: '6dedfaec3a9ff3368b40c583b70568ea'`
@etiennebrosse will you look at it?

**Comment by lausdahl** [comment]
What release bundle is this?

or is this no longer relevant if so please close the issue.

**Comment by etiennebrosse** [comment]
Fixed in https://github.com/into-cps/into-cps.github.io/commit/a15d9ab77a5787f61332b67c72ee7805c52ca8c0
tested under Windows 64

**Comment by ldcouto** [comment]
Great.
