### ISSUE TITLE
Invalid of corrupt jar file Overture-fmu.p2.jar

### ISSUE THREAD

**Issue by avh-agrointelli** [into-cps/intocps-ui#213]
In the INTO-CPS App latest release, the Overture FMU Import / Exporter - Overture FMI Support (0.1.6) download is invalid or corrupted.
![bug-overture-fmu_p2](https://cloud.githubusercontent.com/assets/25738384/22876572/ae42a7f2-f1d1-11e6-9bdb-490d5fa6e585.gif)

**Comment by CThuleHansen** [comment]
I cannot replicate this. It works fine here.
@lausdahl can you try?

**Comment by lausdahl** [comment]
I can also not reproduce this using release bundle `0.0.12`

**Comment by CThuleHansen** [comment]
@avh-agrointelli can you try again?

**Comment by avh-agrointelli** [comment]
@CThuleHansen I still get the same error using bundle 0.0.12, as well as bundle 0.0.11

**Comment by CThuleHansen** [comment]
@ldcouto  can you give this a go?

**Comment by ldcouto** [comment]
Not at work. The download manager doesn't work behind a proxy.

I can check when I get home. Is there any chance this is a platform issue?

**Comment by ldcouto** [comment]
I can download for both versions of the bundle.

I tested on a Mac. @CThuleHansen you tested windows?

<img width="676" alt="screen shot 2017-02-13 at 19 47 23" src="https://cloud.githubusercontent.com/assets/582801/22900225/73d9d3ca-f225-11e6-8275-e1955a835008.png">

**Comment by avh-agrointelli** [comment]
I use Windows 10 and I can download the file. I just can't install it, because the file is invalid or corrupted. Sorry if I was not clear enough

**Comment by CThuleHansen** [comment]
@ldcouto  can you open it?

**Comment by CThuleHansen** [comment]
@avh-agrointelli can you state the steps you perform to detect this invalidity/corruption?
What do you do with the file after downloading it?

**Comment by avh-agrointelli** [comment]
@CThuleHansen After I download the file using the INTO-CPS App Download Manager, which works fine, I go to the <into-cps-projects\install-downloads> folder, and try to run the downloaded .jar file. Then is when I get the message shown above. 
I have also tried opening it with Overture, but I also get the same message.

**Comment by ldcouto** [comment]
This worked for ne,

**Comment by avh-agrointelli** [comment]
@CThuleHansen Thanks, that worked.

**Comment by ldcouto** [comment]
Excellent, closing this issue.
