### ISSUE TITLE
VSI_bundle_v0_0_12 - bash configuration

### ISSUE THREAD

**Issue by avh-agrointelli** [into-cps/intocps-ui#214]
Firstly, I can't find the INTO-CPS App install user manual... so when installing the VSI_bundle_v0_0_12 I don't know how to proceed when I need to provide the path to the bash
![bug-bash_file](https://cloud.githubusercontent.com/assets/25738384/22876768/939dce1c-f1d2-11e6-8b72-7a277935bfab.gif)

**Comment by CThuleHansen** [comment]
@FlorianLapschies can you help out?

**Comment by ldcouto** [comment]
The app manual is at https://github.com/into-cps/into-cps.github.io/raw/master/manuals/INTO-CPS_User_Manual.pdf

There is a link to it on the download page: http://into-cps.github.io/download/

**Comment by FlorianLapschies** [comment]
@avh-agrointelli: You can skip that step during installation. Sect. 7.1.1 of the INTO-CPS user manual provides more information.
@ldcouto: Thank you for the link to the manual.

**Comment by avh-agrointelli** [comment]
@FlorianLapschies Ok, thanks.
@ldcouto Thanks for the link to the manual.

**Comment by ldcouto** [comment]
No problem.
