### ISSUE TITLE
App needs to run on C: drive

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#221]
This is the oddest one yet.

If I have the app in the D: drive and start it, nothing happens. You get the spinning thing next to your mouse for a while and then it disappears but the app never loads.

Starting from the command line also dies silently.

```
D:\into-cps-app-2.1.8-win32-x64>into-cps-app-2.1.8.exe

D:\into-cps-app-2.1.8-win32-x64>
```

This could be some weird permission on my end, but I'd like someone else to test this. @CThuleHansen , do you have 2 disks?

**Comment by CThuleHansen** [comment]
Hmm no, but i'll give it a go on a USB drive on Monday.

**Comment by CThuleHansen** [comment]
Just tried it on a USB drive, and it runs fine.
However @lausdahl is experiencing issues running it on a mapped network drive.

**Comment by ldcouto** [comment]
That's probably it.
 
Our D: drive is actually a mapped drive to a folder in C:

I don't particularly care to investigate this. We can just update the release notes or something.

**Comment by ldcouto** [comment]
Updated release notes template to mention this limitation.
