### ISSUE TITLE
Debugger not working

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#223]
For some app views (such as co-sim) the debugger does not work. We can set brekapoints but the execution doesn't actually suspend.

**Comment by ldcouto** [comment]
This is very closely coupled to #203 

If we run the packaged app, the debugger will run fine. There is some weirdness going on when we run from npm start.

**Comment by CThuleHansen** [comment]
Are different versions used for packaging and jsut running?

**Comment by ldcouto** [comment]
Our versions:
```
"electronVersion": "1.2.1"
    "electron": "~1.4.15",
    "electron-packager": "~7.0.3"    
```

**Comment by ldcouto** [comment]
Packager uses electron 1.2.1 for packaging.

```
$ gulp package-win32
[10:50:12] Using gulpfile ~\projs\intocps-ui\gulpfile.js
[10:50:12] Starting 'package-win32'...
Packaging app for platform win32 ia32 using electron v1.2.1
```

**Comment by CThuleHansen** [comment]
Works fine without source maps and just regular debugging with js

**Comment by ldcouto** [comment]
Via npm start?

**Comment by CThuleHansen** [comment]
Disabled uglify 

```
// Compile TS->JS with sourcemaps. Also move it into the outputfolder
gulp.task("compile-ts", function () {
    var tsResult = gulp.src(tsSrcs)
        .pipe(sourcemap.init())
        .pipe(tsProject());

    return tsResult.js//.pipe(uglify({preserveComments: 'license'}))
        .pipe(sourcemap.write())
        .pipe(gulp.dest(outputPath));
});
```

and did npm start
and in the app debugger I disabled sourcemaps in settings
http://stackoverflow.com/questions/35002087/how-do-you-disable-source-maps-in-chrome-developer-tools

**Comment by CThuleHansen** [comment]
Maybe it is because of the uglify in general?

**Comment by CThuleHansen** [comment]
and we should only uglify when packaing

**Comment by ldcouto** [comment]
Can confirm it's uglify. I managed to debug with TS by having uglify disabled.

The problem is that we only have 1 build task which is used to build the debug and packaged version of the app. 

I'll need to rework the gulpfile a little so we have a build task for debug and one for packaging. In the meantime, I will disable uglify to restore the debugging.

**Comment by CThuleHansen** [comment]
Cool

**Comment by ldcouto** [comment]
Done

Jenkins job needs to be updated. The new package task automatically cleans the repo and runs the uglified build (no need for explicitly calling gulp build)
