### ISSUE TITLE
Traceability graph is no longer shown

### ISSUE THREAD

**Issue by cfjkoenig** [into-cps/intocps-ui#225]
I have downloaded the App (2.2.1 RC, Win64), all of a sudden, the traceability graph does no longer show anything, when I right-click on "traceability" and select "view traceability graph". It works fine with Version 2.1.10 RC.

In the <install_dir>, I have the "neo4j-community-3.1.1" folder, I use Windows 7 (64bit)

By the way: changing the port of the traceability daemon in the settings seems to have no effect. After saving the settings, closing the app and restarting, the default port 8083 is set again.

[update: I have tried the same with the 32-bit version of the app, same problem]

**Comment by ldcouto** [comment]
Hi Christian,

What do you mean " no longer show anything" ?

I can see the browser, but the graph is empty (see attached)
![untitled](https://cloud.githubusercontent.com/assets/582801/23860987/84d04b00-0800-11e7-8e0d-f7c8f517ce64.png)

**Comment by cfjkoenig** [comment]
Hi Luis,

I cannot even see this browser view, the panel is just empty. I have been in contact with @joshoell about this issue, and it turns out that Neo4J does not start on my machine with this RC. I can start in manually though (using the commands described in the wiki). The Neo4J DB seems to start for Jos from the App 2.2.1. RC though. (by the way, my system settings tell me that I have Java version 8 update 101 (Build 1.8.0_101-b13) installed).

**Comment by ldcouto** [comment]
I know Jos did some tweaks to that, but I think it was only for Linux. In any case, can you try the latest build at http://overture.au.dk/into-cps/into-cps-app/master/Build-278_2017-03-13_14-30/ ?

**Comment by ldcouto** [comment]
@cfjkoenig , is this occurring with the new release?

**Comment by cfjkoenig** [comment]
@ldcouto : yes, I still have the same problem, @joshoell is currently working on ways to find the error; it seems that Neo4J is not starting correctly. I'll let you know once we found something.

**Comment by joshoell** [comment]
Fixed by commit 7bd486934e39b156b33108d1a95344891a694ea3
