### ISSUE TITLE
Change default project location used on Windows from `HOME\into-cps-projects` to `HOME\Documents\into-cps-projects`

### ISSUE THREAD

**Issue by lausdahl** [into-cps/intocps-ui#226]
It is difficult to find the other folder in windows

**Comment by ldcouto** [comment]
This is already possible in the settings. I assume you mean changing the default location, so I'm changing the title.

I actually prefer the Home folder, but I don't care either way.

**Comment by ldcouto** [comment]
@lausdahl status on this?

**Comment by lausdahl** [comment]
I just raised the issue because I noticed that its not easy to reach this location through the finder in Windows. I'm not using Windows my self.

**Comment by ldcouto** [comment]
Folder Switched. Can you check `ldc/226` and see if it's still fine on Mac?

**Comment by lausdahl** [comment]
Would it be bad only to change the location for windows. I also prefer the $home location on *nix systems.

**Comment by ldcouto** [comment]
Pushed new change. Should work on windows only now. Can you please check?
