### ISSUE TITLE
Crash at launch "A Javascript error occured in the main process"

### ISSUE THREAD

**Issue by Cien02** [into-cps/intocps-ui#227]
I launched the COE (ans it says is running )but the "simulate" button was still disabled so i reload the view and the app just crashed. The following error always appear when i try to launch the app ever since:
![image](https://cloud.githubusercontent.com/assets/22459060/24291029/2a39d2ec-107f-11e7-86b0-08fdb38351aa.png)

I am working on windows 8.1 (64 bit) and originally used v2.2.0 of the INTO-CPS app. 
I have tried new install of the app, tried different versions and tried launching from different drive but always similar error. (The error screenshot was from v3.0.0)

**Comment by ldcouto** [comment]
Hi @Cien02 

From the look of it, I'd say you have a corrupted settings file.

By default it is located at `Users\{USER}\AppData\Roaming\INTO-CPS APP\intoCpsApp\settings.json`

Can you try deleting this file and restarting the app?

**Comment by Cien02** [comment]
Hi @ldcouto 

Deleting that file indeed fixed the issue, Thanks!

**Comment by ldcouto** [comment]
Cool. Glad to hear it.
