### ISSUE TITLE
[import example project] downloading dialog box

### ISSUE THREAD

**Issue by astefano** [into-cps/intocps-ui#228]
Hi,

Just to note that if one imports a project already imported, the downloading dialog box doesn't close and the progress bar stays with 0%.

Cheers,
lacramioara

**Comment by ldcouto** [comment]
Hi

Are you import the project to the same location?

**Comment by astefano** [comment]
yep

**Comment by ldcouto** [comment]
Odd. I cannot reproduce this. For me, the box closes after a few moments.

Can you give a bit more information about your system and app version?

**Comment by astefano** [comment]
i run into-cps 3.0.0 on a windows 7 machine. i attach a screenshot with the
download box remaining open. but if people can't reproduce it, maybe it's
smth with my system. anyhow it's a very minor issue, feel free to close it
if it's of no importance to you.

**Comment by CThuleHansen** [comment]
It seems like we have people encountering this issue every once in a while, but we have not been able to pinpoint the issue

**Comment by ldcouto** [comment]
I can't reproduce on MacOS. 

On Win7 the git import always hangs at 0 for me, regardless of existing folders. But I think this is due to some local OS settings.

I think the best we can do right now is add a note to the known issues about the less-than-perfect state of the importer.

**Comment by CThuleHansen** [comment]
Agreed

**Comment by ldcouto** [comment]
Wiki page updated. Archiving for now.
