### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#229]
The download manager and examples importer don't work if we are behind a proxy (the Git importer works if the proxy is set in the .gitconfig).

Not having the download manager working behind a proxy is a real problem. It becomes a lot harder to run a co-simulation (you have to manually download, create the install folder, move the COE there and rename it). This takes away one of the biggest strengths of the app which is ease of co-simulation.

@lausdahl @CThuleHansen are you guys familiar with the download manger? What would be the effort required to add support for proxies. I am willing to do the work, but I'd like an idea of the effort.

**Comment by lausdahl** [comment]
I think all downloads happen in this file https://github.com/into-cps/intocps-ui/blob/master/src/downloader/Downloader.ts it was @afterkelsen who wrote it, but I dont know how proxies should be configured for it

**Comment by ldcouto** [comment]
Hmm. While mucking about with this, I've found a way to pass the proxy settings to the app. It's script based, but works (for reference you must have the HTTP_PROXY env var set, even on Windows).

I think I  will document that in the Wiki and be done with it.

**Comment by ldcouto** [comment]
Updated releases notes. That will have to suffice for now.

**Comment by CThuleHansen** [comment]
Good job!
