### ISSUE TITLE
Clicking on the download manager "Release: 0.0.12" entry no overview appears

### ISSUE THREAD

**Issue by idhugo** [into-cps/intocps-ui#232]

**Comment by ldcouto** [comment]
Yeah, the json file for 0.0.12 is broken. @etiennebrosse seems like it was your commit eb519e0be8a7d34456e3680a3b14d40c8047e3f4 that did it.

I ran the json file through https://jsonlint.com/ and it found an error, though I can't make much sense of it. Can you take a look?

**Comment by lausdahl** [comment]
I'm closing this since it appears to be fixed the expected list of downloads are shown in the app for 0.0.12 now
