### ISSUE TITLE
Instance is not saved when single FMU has no connection

### ISSUE THREAD

**Issue by cabralfortiss** [into-cps/intocps-ui#235]
I tried to test a single FMU with one output. Of course, the output is not connected to anywhere, but I'd to see its behavior. Unfortunately, in the Configuration in the Multimodel tab, the instance of the FMU is not saved, and therefore I cannot simulate it.

I added a dummy input to the FMU, and connected the output to it, and then the instance is saved.

**Comment by ldcouto** [comment]
Confirmed.

@CThuleHansen can you take a look?

**Comment by lausdahl** [comment]
The COE is for co-simulation not for FMU testing. Use the https://trac.fmi-standard.org/browser/branches/public/Test_FMUs/Compliance-Checker for this.

You need at least two instances to perform a co-simulation and at least one output and the instances must be connected. The app may have some limitations where it does not let you create multiple instances of the same FMU to each other (although the COE itself should be able to handle this).

**Comment by CThuleHansen** [comment]
I will look into the app

**Comment by cabralfortiss** [comment]
But I don't want to check my FMU, I want to simulate it. Wouldn't it be nice if the co-simulator COE also works as just a simulator? What would be the problem for the COE to co-simulate the FMU with nothing else?

**Comment by CThuleHansen** [comment]
This issue is related to the way instances are modelled. Instances exists as part of connections, as they otherwise make no sense in a Co-Simulation. Therefore an unused instance is removed.

**Comment by ldcouto** [comment]
Alright. It's not worth changing the project model.

Best I can do is suggest the following obvious workaround:

To simulate a standalone FMU, just create a second dummy FMU to absorb (and ignore) output signals.

**Comment by cabralfortiss** [comment]
If is not technically a bug, and it would require a big change, I'll keep with the workaround. Thanks!

**Comment by ldcouto** [comment]
Cool, thanks for your understanding.
