### ISSUE TITLE
Values of boolean parameters are always resets to true 

### ISSUE THREAD

**Issue by kgpierce** [into-cps/intocps-ui#236]
When I try to set "DE_ONLY" to false (see image below) it is always automatically changed to true when focus is lost.

![image](https://cloud.githubusercontent.com/assets/5968335/25903722/2bf23cba-3595-11e7-806c-5dfd5990a449.png)

**Comment by ldcouto** [comment]
Where is this dialog? FMU parameters?

**Comment by lausdahl** [comment]
The is a parameter for an FMU. Scalar variable example:

```xml
<ScalarVariable name="dummy" valueReference="3" causality="parameter" variability="fixed" initial="exact"><Boolean start="false" /></ScalarVariable>
```
