### ISSUE TITLE
DSE download error

### ISSUE THREAD

**Issue by avh-agrointelli** [into-cps/intocps-ui#242]
I encountered an error when trying to download the Design Space Exploration - Scripts for generating and analysing multiple co-simulations (0.2.0) from the download manager.

The error says:
Invalid Checksum
Bad MD5 expected: 'a7c916f74981e526bcbc9dc22d9898aa' got: 'dabf7b8cc338587bf8ad11ba6317e415'

Is it maybe because of my internet connection?

PS: attaching files does not work neither from the app's Help > Report Issue

**Comment by ldcouto** [comment]
The checksum in the current version of the DSE download is incorrect.

The fix should come online later today when the new bundle comes out.
