### ISSUE TITLE
Problematic traceability integration when working with multiple branches and inconvenient when using INTO-CPS for co-sim only

### ISSUE THREAD

**Issue by lausdahl** [into-cps/intocps-ui#245]
During the summer school in Sibiu we discovered that the traceability implementation is partly not wanted for visitors that are only interested in co-simulation, and the current implementation does not make it easy to disable it.

Furthermore, the current implementation does not work when using git with more than one branch since the database does not merge or diff. A simple illustration of this is just run a few simulations from a case study, then wait until someone else did the same and pushed. If you then pull git get into unsolvable trouble.

I recommend that we:
* disable traceability by default, allowing users to decide if they want the extra feature
* implement a clearly visible indication in the App showing if traceability is on. Maybe a thin status bar with a Traceability (green|red) indicator
* fix the issue with the database that doesn't merge

For the latter I would suggest something simple to start with e.g.

Take all messages send to the daemon that are otherwise inserted into the database and also:
* remove all whitespace
* calculate the git hash of the content
* create a new file under ./Traceability/db/ using the git hash as file name e.g. for the trace message `{trace-info}` we could create the file `./Traceability/db/17864ee22675e3d3dbb8a8d17d8b01ce8148d3c5 containing that message
* call git add -f on the new file.

```bash
echo '{trace-info}' | git hash-object -w --stdin

17864ee22675e3d3dbb8a8d17d8b01ce8148d3c5
```
* on daemon load we always start with an empty db and insert all content of `./Traceability/db/*` into the database.

Doing something like this will probably work fine for the project, it should work for merge and you should not lose traceability data that way. It is also very simple to implement. Only small drawback is that we might have multiple trace files containing the same info which should be filtered in import (this is of cause a theoretical issue, not likely to happen)

I'm adding Luis since I do not know who is the developer who should do this since the guy implementing the daemon no longer is assigned to the project.

**Comment by ldcouto** [comment]
@mi-hofmann is the new developer from TWT on traceability. Hopefully he can comment on this.

I support disabling traceability by default, especially since it requires Neo4J. Can we do this immediately? PR #246 seems like a good place

The other features, we need to think more on. 
* I recall we decided that multi-user traceability was out of scope. 
* A visual indicator is certainly useful, but I'd put that at lower priority than the actual query UI

**Comment by CarlGamble** [comment]
I also think disabling traceability by until it is more stable/complete could be  a good idea.

**Comment by lausdahl** [comment]
Concerning: "I recall we decided that multi-user traceability was out of scope." then the issue here is that a single user also gets into trouble if he works with multiple branches which is kind of expected since we use git

**Comment by ldcouto** [comment]
I guess that's a valid point, but the explicit version control of Git branches should not be getting tangled up in the traceability DB.

Maybe the use of Git needs to be rethought?

**Comment by ldcouto** [comment]
From today's discussion:
* we store one file per message in order to ensure smooth merging
* we need to inform users to reload the traceability DB when they switch branches. To help with this, we'll provide a `Reload Project` button.
