### ISSUE TITLE
Open Project emit error

### ISSUE THREAD

**Issue by lausdahl** [into-cps/intocps-ui#251]
I often get this error when I open projects. I do not know how to provoke it:

![image](https://user-images.githubusercontent.com/2575418/28224112-2a2dcde2-68ce-11e7-9c33-ef60923dbb9d.png)

**Comment by ldcouto** [comment]
I have never seen this error, either on Mac or Windows. Is the project folder missing or something?

**Comment by lausdahl** [comment]
Happens quite often for me. Played a bit with it and it happened at least every 3-4 times and once it’s there it required a restart of the app to get rid of it.

I checke the project and all is ok at the file level.

Regards,

Kenneth Lausdahl
kenneth@lausdahl.com

**Comment by ldcouto** [comment]
Hmm. Does it happen in the packaged app, npm version or both?

**Comment by lausdahl** [comment]
both

**Comment by ldcouto** [comment]
good. I mean, in a sense that it's a code issue.

Have you ever seen this error on Win or Linux?

**Comment by lausdahl** [comment]
I dont remember. But it also seen it on mac during project creation, which makes sense since it opens the project right after creation.

**Comment by ldcouto** [comment]
Ok... 

I'm not sure what we can do for now except try to isolate it. Let's see if anyone else has experience this error.

L

**Comment by ldcouto** [comment]
This seems to have gotten worse recently, whether due to to #267 or something else.

@lausdahl your idea to work around it seems good.
