### ISSUE TITLE
FMU builder doesn't load / certificate error

### ISSUE THREAD

**Issue by kgpierce** [into-cps/intocps-ui#254]
It looks like the FMU builder has a problem with its certificate? In the App this leads to a blank pane, but in Chrome I can navigate to https://sweng.au.dk/fmubuilder and add a security exception, then it works fine.

Not sure if this is just on Newcastle campus or a wider problem.

**Comment by ldcouto** [comment]
Can confirm the same error shows up here.

**Comment by kgpierce** [comment]
Chrome says NET::ERR_CERT_DATE_INVALID.

**Comment by lausdahl** [comment]
Yes I did not manage to install the new one before I vent on vacation all domains should be updated now
