### ISSUE TITLE
Return value from "simulate"

### ISSUE THREAD

**Issue by gmeisl-twt** [into-cps/intocps-ui#257]
According to its API documentation, the COE returns a json with the content {"status":"simulating", ...} when it receives a "simulate" command.
In my case the COE only replies when the simulation is done and then returns the status "Finished".
Please update the documentation (if possible please also add how one can get the COE to return the "simulating" message immediately, not waiting for the simulation to be finished).

**Comment by lausdahl** [comment]
I will update the documentation. You should be able to call the status command to get the current status of a simulation.

**Comment by lausdahl** [comment]
this is fixed in next COE release version `0.2.12`
