### ISSUE TITLE
Re-enable responsive HTML

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#26]
The initial layout we had using bootstrap was responsive so it would actually wrap content and stuff as you resized the pages.

When we moved to the 2 pane layout from jquery, the responsiveness went away. Would be good to re-enable it.

**Comment by CThuleHansen** [comment]
https://github.com/into-cps/intocps-ui/commit/d2bfa14a721f187706c4380bf6c612760094f5bb
