### ISSUE TITLE
unzip of the FMU does not maintain the permissions

### ISSUE THREAD

**Issue by tfabbri** [into-cps/intocps-ui#270]
I noted that during the unzip of the FMU, the unzipped directory does not maintain the permissions of the contained files. 
More precisely, the FMU that I am working with contain a separate executable that when unzipped under `/tmp/` has lost the `x` permission. Without the correct permissions I am not able to run correctly the co-simulation.

**Comment by tfabbri** [comment]
With the last snapshot of the  `coe` the issue is solved for linux-32bit

**Comment by lausdahl** [comment]
this is fixed in coe 0.2.14 which is in the dev bundle now and will be released soon. Just switch to development mode to use it.
