### ISSUE TITLE
Show comments for signals and parameters in App at mouse-over

### ISSUE THREAD

**Issue by cfjkoenig** [into-cps/intocps-ui#272]
It would be nice to display the Annotations (from the ModelDescripton.xml) to signals or parameters at MouseOver in the App / Multi-model, if they are available. This could be an enhancement to the INTO-CPS app.

**Comment by ldcouto** [comment]
What Annotations do you mean, can you give an example? 

Maybe it's my FMUs but here is a parameter entry. I don't see anything that's really useful to show.
```
<ScalarVariable name="TempDriftDuration_Sec"
 valueReference="6"
 causality="parameter"
 variability="fixed" 
initial="exact">
<Real start="-1.0" />
</ScalarVariable>
```

Do you mean vendor annotations (see below) They don't seem very useful.
```
	<VendorAnnotations>
		<Tool name="Overture">
			<Overture>
				<link valueReference="0" name="System.hwi.sr2_spIn.value" />
				<link valueReference="1" name="System.hwi.dbg_temp.value" />
				<link valueReference="2" name="HardwareInterface.chillerAdjust.value" />
				<link valueReference="3" name="System.hwi.z2_spOut.value" />
				<link valueReference="4" name="HardwareInterface.smaxt.value" />
				<link valueReference="5" name="System.hwi.sr1_spIn.value" />
				<link valueReference="6" name="HardwareInterface.dt.value" />
				<link valueReference="7" name="System.hwi.sr2_temp.value" />
				<link valueReference="8" name="System.hwi.z1_spIn.value" />
				<link valueReference="9" name="System.hwi.z2_spIn.value" />
				<link valueReference="10" name="System.hwi.sr1_temp.value" />
				<link valueReference="11" name="System.hwi.cm.value" />
				<link valueReference="12" name="System.hwi.z1_spOut.value" />
				<link valueReference="13" name="System.hwi.initial_csp.value" />
				<link valueReference="14" name="System.hwi.sr2_spOut.value" />
				<link valueReference="15" name="System.hwi.csp.value" />
				<link valueReference="16" name="HardwareInterface.dv.value" />
				<link valueReference="17" name="HardwareInterface.smint.value" />
				<link valueReference="18" name="System.hwi.dbg_setpoint.value" />
				<link valueReference="19" name="System.hwi.dbg_driftval.value" />
				<link valueReference="20" name="System.hwi.z2_temp.value" />
				<link valueReference="21" name="System.hwi.z1_temp.value" />
				<link valueReference="22" name="System.hwi.faults.value" />
				<link valueReference="23" name="System.hwi.dbg_drifttime.value" />
				<link valueReference="24" name="System.hwi.sr1_spOut.value" />

			</Overture>
		</Tool>
	</VendorAnnotations>
```

**Comment by cfjkoenig** [comment]
Yes, an example would be in the ModelDescription.xml: 

<ModelVariables>
	</ScalarVariable>
	  <ScalarVariable name="pAtm" valueReference="7" description="height, used as state"
                  causality="output" variability="continuous" initial="exact">
</ModelVariables>

The "description" an optional attribute. Its described in the FMI 2.0 standard on page 45&46.

**Comment by ldcouto** [comment]
I see. I think this is a relatively low value feature. Not all exports have descriptions and I don't see other entries that are very useful to show.

**Comment by cfjkoenig** [comment]
I agree that it is probably not the highest priority. It is rather an idea for an enhancement which we wanted to document somewhere, and the issue tracker seemed like the natural choice for this.

**Comment by ldcouto** [comment]
Yes, thank you for adding it.

We have a milestone for exactly these suggestions. I will archive this there.
