### ISSUE TITLE
Graph plotting sometimes stops before end time

### ISSUE THREAD

**Issue by lausdahl** [into-cps/intocps-ui#289]
If I run simulations of the single watertank with coe 0.2.18 then I sometimes gets this: 

![image](https://user-images.githubusercontent.com/2575418/32270911-065e9b14-bef8-11e7-9c3a-012ddf093614.png)

I added debug info on WS receive and it gets the data as shown end time is 10

**Comment by CThuleHansen** [comment]
Fixed in 70ca181a7912b987d365f6821e4d25881c9c35e5
