### ISSUE TITLE
Different context menus based on element clicked

### ISSUE THREAD

**Issue by CThuleHansen** [into-cps/intocps-ui#29]
The different items in the browser will probably need different contextmenus.
This can be implemented using the event [contextmenu](http://w2ui.com/web/docs/w2sidebar.onContextMenu). E.g.: 
```
this.tree.on("contextMenu", (event: Object) => {
            console.log(event);
        });
```
And then setting the menu: http://w2ui.com/web/docs/w2sidebar.menu

**Comment by lausdahl** [comment]
This is done in: 5faabfc51fa0054c834eb930018627afe88630da
