### ISSUE TITLE
Live Plotting in external Window does not work

### ISSUE THREAD

**Issue by gmeisl-twt** [into-cps/intocps-ui#290]
When I activate the option to show a Plot in an external window the plot is empty most of the times.

![grafik](https://user-images.githubusercontent.com/25317386/32363664-b83bb1d6-c070-11e7-947e-a9ea6e658ab0.png)

**Comment by CThuleHansen** [comment]
Should be fixed in a04cd27602f316dbc058bd1fb8ad78f8d9608405
