### ISSUE TITLE
COE log override no longer prints to command line

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#293]
Consider the config below:

![untitled](https://user-images.githubusercontent.com/582801/32729047-704f18ec-c87a-11e7-8af0-19bf4eafcf3d.png)

If this is executed with a COE launched by the command line, then only warnings or higher get printed.

![untitled](https://user-images.githubusercontent.com/582801/32729205-e422ef46-c87a-11e7-9e5e-14d7f5553bc5.png)

It works normally for COEs launched from within the app, but it's quite inconvenient for externally launched ones (which is very common -- for example, for log redirecting)

**Comment by lausdahl** [comment]
This happens as a side effect of the optimisation of the integration into App. All the information is included in coe.log.

**Comment by ldcouto** [comment]
Does that mean this cannot be fixed?

**Comment by lausdahl** [comment]
yes we cannot both have it print and filter. So the log levels you add here are also overriden and the output is shown in the coe.log file.

There is a filter applies in the log4j.properties in the COE if you delete the filter it works like before. But then both consoles in the app will show the same.

**Comment by ldcouto** [comment]
meh. This is annoying, cause the coe.log has info from multiple runs. But if it's not possible, I'll live with it.
