### ISSUE TITLE
Fire Traceability Triples

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#34]
The app will need to register various action with the traceability daemon. These tuples still need to be precisely defined but the actions will be something like:
- create multimodel from connections mapping
- create co-sim configuration from multimodel
- modify co-sim configuration
- run co-sim configuration

Similar tasks may be needed for DSE, MC, etc. Right now, we're not sure whether deletions will be traced.

**Comment by ldcouto** [comment]
@joshoell , this needs to be taken up soon. Do you guys have anyone that can take care of it?

**Comment by ldcouto** [comment]
@lausdahl   this is implemented in PR #208 right?

**Comment by lausdahl** [comment]
yes already in master

**Comment by ldcouto** [comment]
Cool.
