### ISSUE TITLE
Standardize Naming Rules

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#35]
Things are a mess right now. Some filenames are CamelCase and some are all lowercase. Even in the camel case ones, some start with capital letters (PascalCase) and others don't (camelCase).

There is also no consistency in terms of relating file names to the classes they define. 

If we combine this with the case sensitivity of the different OSes and the import mechanism of JS, we have a recipe for problems.

We really need to go in and make things a bit more consistent. Since this will affect everyone, we can freeze the repo for a day or 2 while we do this. Post M18 (or even during it) seems like the best time to do it.

@lausdahl @CThuleHansen , we discussed this a bit in Stuttgart. Can you help me nail down some rules? I searched around a bit and found some stuff so here is what I suggest.
- Module, type and class names should be CamelCase (sometimes called PascalCase too)
- file names should be all lowercase. The dash (`-`) can be used to supply basic modularisation when necessary. Example: `intocpsapp-events.ts`
- folders also be all lowercase. By convention, we name folders with the initials of the relevant feature.
- it is up to individual developers to sort classes into files but for any complex class, a 1-to-1 relation with its source file is probably a good idea

What do you think?

Refs:
http://stackoverflow.com/questions/31213908/recommended-file-naming-convention-for-typescript
http://stackoverflow.com/questions/7273316/what-is-the-javascript-filename-naming-convention
https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines

**Comment by lausdahl** [comment]
I agree with the lock down of the repo and then one or us corrects it all.

We use this `import * as Collections from 'typescript-collections';` currently, they seem to have a nice scheme in place.

It looks like they have a one-to-one for classes internally but exposes a single lowercased file as the namespace where they declare the exports. For the lowercased file they also use the `-` you mentioned above. This namespace structure is nice to work with.

**Comment by ldcouto** [comment]
Yeah, this is not happening during INTO-CPS.
