### ISSUE TITLE
Create glyphicon's for Overture, 20sim, Open Modelica, Modelio, and connections file

### ISSUE THREAD

**Issue by lausdahl** [into-cps/intocps-ui#41]

**Comment by ldcouto** [comment]
How about this:

Connections: ![cons](https://cloud.githubusercontent.com/assets/582801/15375273/12c87686-1d46-11e6-8762-6d1df22e7cab.png)

Overture: ![ovt](https://cloud.githubusercontent.com/assets/582801/15375343/78908f30-1d46-11e6-8324-db707970e5d3.png)

OpenModelica: 
![om](https://cloud.githubusercontent.com/assets/582801/15375346/8184dcf4-1d46-11e6-9f3b-47d663dfc81d.png)

20-Sim: ![20sim](https://cloud.githubusercontent.com/assets/582801/15375352/899dd06c-1d46-11e6-90c7-5ef3c8b20452.png)

Modelio: ![modelio](https://cloud.githubusercontent.com/assets/582801/15375356/9411911e-1d46-11e6-9e3c-58e5d4686f72.png)

They are SVGs and quite easy to turn into icons via https://icomoon.io/

**Comment by lausdahl** [comment]
I think the logos should be the original ones:

**Comment by lausdahl** [comment]
![256x256](https://cloud.githubusercontent.com/assets/2575418/15375806/9d507870-1d51-11e6-9766-a6dac35cb5c2.png)

![overture_icon_128x128](https://cloud.githubusercontent.com/assets/2575418/15375803/95976fda-1d51-11e6-8d9a-1b83b230d3f8.png)

![20-sim icon](https://cloud.githubusercontent.com/assets/2575418/15375817/adb55442-1d51-11e6-91e9-c4af3fb04766.png)

![om](https://cloud.githubusercontent.com/assets/2575418/15375819/b1199666-1d51-11e6-9b4c-54693c28a580.png)

**Comment by ldcouto** [comment]
That can work too but:
* everything else in the tool is black and white so it will clash
* those logos are not SVG. We'll have to ask the guys for those versions

Should we get someone else to vote on this?

**Comment by ldcouto** [comment]
SVGs Got:
- [x] Overture
- [ ] 20-Sim
- [ ] Modelio
- [ ] Open Modelica

**Comment by lausdahl** [comment]
No go for the coloured ones, the other icons also has colours in my version e.g. folders are yellow. This way we dont have to explain the icons since they will match the filesystem icons (at least for windows)

**Comment by ldcouto** [comment]
Yeah ok. I got the Overture one from our repo

I'll ask the other guys for their tool icons.

**Comment by ldcouto** [comment]
Only modelica missing

**Comment by ldcouto** [comment]
Done in c05886ca29

Just missing RTT because I do not see it on any of the projects.

**Comment by ldcouto** [comment]
I just saw in the demo today that RTT projects already have their icons
