### ISSUE TITLE
Create UI for the Download Manager

### ISSUE THREAD

**Issue by lausdahl** [into-cps/intocps-ui#42]

**Comment by lausdahl** [comment]
Some basic UI is added in 82be709ae0d6d2c88fa4a3d5653a76a37777e298 it allows basic download to a download folder inside the project. The install and launch features are not currently called and dont have UI support

**Comment by ldcouto** [comment]
Does this include the COE?

**Comment by lausdahl** [comment]
yes COE is there now. It just downloads it.

it does all what Anderes tool did up to the install phase which I did not add, not completely sure how this should work. The API for calling it is there so just need to get the workflow clarified for this part. It should just take an hour or two to add these calls if the user workslow is more or less strait forward ( I in general just dont like tools to auto install stuff)

**Comment by ldcouto** [comment]
Cool. I guess all that's left is starting the coe when we launch co-sims.

Once that's done we can try the alpha.

By the way,  I'm with you on auto installs. Not a fan at all.

**Comment by lausdahl** [comment]
The COE is downloadable and can be started from the *COE Server status*

**Comment by lausdahl** [comment]
See #55 for further improvements.
