### ISSUE TITLE
path is missing extension when passed to menuhandler

### ISSUE THREAD

**Issue by CThuleHansen** [into-cps/intocps-ui#48]

**Comment by FlorianLapschies** [comment]
Should be fixed in commit 3d6f681d14f7edc9e62eaaa23ff9bd540cd63a8f.

    Fix loading multi-model and coe view.
    
    In the project browser the actions associated with *.mm.json and
    *.coe.json files are merged with the containing directory.
    This also means that actions referring to these files must have
    their path and not that of their parent directory as argument.
