### ISSUE TITLE
Examples won't download if git is not available in the path

### ISSUE THREAD

**Issue by richardpayne** [into-cps/intocps-ui#57]
I've tried opening project examples from the release candidate. This is what I’ve been trying:

1)      Click File>Open Project Examples
2)      the ‘Open Examples’ window opens
3)      select “Case Study: XXX” and click “Open”

Then nothing happens…

I’ve tried each case study and tried changing the Project root path, but nothing seems to work. I have waited approx. 10 mins. I have cloned the git repositories successfully from GitHub manually and opened the clones directly into the app - this works fine. 

Using Windows 10 and version into-cps-app-win32-x64.

**Comment by ldcouto** [comment]
One more thing you could try is checking if git is available on the path (just open cmd and run `git  --version`)

**Comment by richardpayne** [comment]
Git is not available on the path. Do we need to ensure that git is installed in the app installation process?

**Comment by richardpayne** [comment]
When I added Git to my path the examples downloaded fine.

**Comment by ldcouto** [comment]
Good to know. Thanks for helping track this down Richard. 

I think it will be enough to mention git in the user manual and print an error message: `git not found` or something like that. All agreed?

**Comment by CThuleHansen** [comment]
Fine for me. @lausdahl?

**Comment by lausdahl** [comment]
Agree. 

We need to add a release note which mentions the system requirements for the app. Luis will you create a new issue for this.

**Comment by ldcouto** [comment]
Done. See #62 

I've also edited the release notes. We'll have to add it to the user manual later too. Are there any other requirements?

**Comment by ldcouto** [comment]
Alright, I'm closing this one. We'll track work on the new feature as an enhancement in #62
