### ISSUE TITLE
Different paths for downloaded COE and COE to launch.

### ISSUE THREAD

**Issue by CThuleHansen** [into-cps/intocps-ui#60]
When the COE is downloaded using the download manager the name is: coe-0.0.4-jar-with-dependencies.jar

When trying to launch the COE via the COE server status it cannot launch the jar because it looks for the file coe.jar. See the error below:
`Error: Unable to access jarfile C:\Users\ctha\AppData\Roaming\INTO-CPS APP\intoCpsApp\tmp\install_temp\coe.jar`

**Comment by ldcouto** [comment]
Related to #59 I assume?

**Comment by CThuleHansen** [comment]
probably yes

**Comment by CThuleHansen** [comment]
It is related to #59. Works when the application is set to developer mode.

**Comment by richardpayne** [comment]
I can confirm this is the same with OSX: 

`(Error: Unable to access jarfile /Users/nrjp6/Library/Application Support/INTO-CPS APP/intoCpsApp/tmp/install_temp/coe.jar)`

**Comment by CThuleHansen** [comment]
A new release will be made available Wednesday.
This release will contain a fix for this.

**Comment by CThuleHansen** [comment]
Fixed https://github.com/into-cps/into-cps.github.io/commit/e450973d92e36b42bccc09e145b1a591cb915df9
