### ISSUE TITLE
COE label does not switch to online

### ISSUE THREAD

**Issue by CThuleHansen** [into-cps/intocps-ui#61]
COE downloaded via download manager 
Manually renamed 
Started via coe server status, but still appears to be offline.
![image](https://cloud.githubusercontent.com/assets/3479481/15868216/1d01ca3e-2ce7-11e6-88c9-17247fbc7fb6.png)

**Comment by CThuleHansen** [comment]
Only works with the new COE, which is available via the download manager when the application is set to developer mode via settings.

**Comment by lausdahl** [comment]
this is because it isnt released yet. First supported version is 0.0.7
