### ISSUE TITLE
Menuhandlers should return promises.

### ISSUE THREAD

**Issue by CThuleHansen** [into-cps/intocps-ui#65]
The process in the menu handlers sometimes does some ascync stuff, but does not use promises. This results in weird erros. E.g.

```
menuHandler.createMultiModel = (path) => {
    $(init.mainView).load("multimodel/multimodel.html", (event: JQueryEventObject) => {
        let project: IProject = require("electron").remote.getGlobal("intoCpsApp").getActiveProject();
        if (project != null) {
            let name = Path.basename(path, ".sysml.json");
            let content = fs.readFileSync(path, "UTF-8");
            let mmPath = project.createMultiModel("mm-" + name + " (" + Math.floor(Math.random() * 100) + ")", content);
            IntoCpsApp.getInstance().emit(IntoCpsAppEvents.PROJECT_CHANGED);
            menuHandler.openMultiModel(mmPath + "");
        }
    });
};
```

`menuHandler.openMultiModel(mmPath + "");` This results in an async operation, and therefore it has to be last in the method, because we do not wait for it. Therefore it should return a promise, so waiting is possibly.

**Comment by ldcouto** [comment]
@CThuleHansen , I don't think we ended up doing anything with this. I want to archive for after INTO-CPS. What do you think?

**Comment by CThuleHansen** [comment]
Yes archive.

**Comment by ldcouto** [comment]
Done
