### ISSUE TITLE
Update relevant settings when development mode is checked/unchecked

### ISSUE THREAD

**Issue by CThuleHansen** [into-cps/intocps-ui#66]
Currently the IntoCpsApp does the following:

```
if (this.settings.getValue(SettingKeys.DEVELOPMENT_MODE)) {
      this.settings.setValue(SettingKeys.UPDATE_SITE, this.settings.getValue(SettingKeys.DEV_UPDATE_SITE));
      this.settings.setValue(SettingKeys.EXAMPLE_REPO, this.settings.getValue(SettingKeys.DEV_EXAMPLE_REPO));
}
```

However, when development mode is checked/unchecked in the settings view it does not affect any other settings and therefore a restart of the app is necessary.

Fix it so settings are reflected immediately when changed.

**Comment by ldcouto** [comment]
Delaying to post INTO-CPS
