### ISSUE TITLE
News feed when opening the app

### ISSUE THREAD

**Issue by CThuleHansen** [into-cps/intocps-ui#73]
Currently the app just states: "Welcome to the INTO-CPS Application".
It would be useful if it contained some more introductory text, e.g. double clicking files, opening coe server status etc.

**Comment by ldcouto** [comment]
As discussed yesterday, we're going to use the welcome page as a news feed. Renaming this issue.

**Comment by ldcouto** [comment]
We'll revisit this after INTO-CPS.
