### ISSUE TITLE
Check for examples updates

### ISSUE THREAD

**Issue by richardpayne** [into-cps/intocps-ui#76]
A feature request: is it possible to have an indication to users of the app of any updates to the examples?  Then as we add new FMUs, different configurations etc to GitHub, then users can grab these...

**Comment by lausdahl** [comment]
A comment, if the same example is checked out on top of the existing one it should do git pull.

**Comment by ldcouto** [comment]
Users can also use any existing git tool to update the examples. At the plenary, we discussed using the welcome page of the app to display a news tracker where things such as new examples could be shown.

See #73 

This request is already covered there.
