### ISSUE TITLE
Project Basic Viewer

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#8]
Tree based view of the project structure.  Based directly off the native FS.

**Comment by ldcouto** [comment]
The view and folder for the browser are now ready (see 17999ae)

**Comment by CarlGamble** [comment]
Great.  I will update my local copy today and have a look.

Carl

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Thu, Apr 28, 2016 at 2:18 PM -0700, "Luis Diogo Couto" <notifications@github.com<mailto:notifications@github.com>> wrote:


The view and folder for the browser are now ready (see 17999ae<https://github.com/into-cps/intocps-ui/commit/17999aee993620e00356b2c64221ab191afba64c>)

-

**Comment by ldcouto** [comment]
To be clear, it's just the 2 pane layout that has been implemented and there is now a place in the git repository where the project viewer code can be developed.

UI-wise, it's just an empty left pane saying "project browser".

I was just trying to say that work can commence on this task. Hope I didn't raise anyone's hope too much :)
