### ISSUE TITLE
Remove unneeded node modules from packaged app

### ISSUE THREAD

**Issue by ldcouto** [into-cps/intocps-ui#84]
Need to fix package.json so the dev modules are properly defined. And we need to see if we can use electron packager in a way that excludes the dev modules.

This needs to be investigated by the end of July. If it's not possible, then we have to move a 2 package.json structure.

**Comment by ldcouto** [comment]
So, if we run electron packager with prune, we can cut the node modules from 471 to 104.

The size of the (unzipped) app does not change too much: 239MB to 185MB.

**Comment by ldcouto** [comment]
The following modules are declared in package.json but seemingly unused:
* electron-debug
* promise

@lausdahl , you added debug and anders added promise. Are these safe to delete?

**Comment by lausdahl** [comment]
I do not remember

**Comment by ldcouto** [comment]
Alright, I'll look into it.

**Comment by ldcouto** [comment]
Done as of eae1d9b
